### ISSUE TITLE
how can I run in production build locally?

### ISSUE THREAD

**Issue by aermike** [chaskiq/chaskiq#108]
Hi 
I want install server for production but not deploy with Heroku
It is possible?
How? I don't find any clear instruction for that

**Comment by Mike97M** [comment]
Same problem here, not sure how to run this locally.

**Comment by michelson** [comment]
Hi , right now we don't have a documentation, I'm sorry. we need to add a capistrano recipe for this. and maybe a chef recipe to provision the VPS.

**Comment by michelson** [comment]
BTW , Chaskiq as an Rails standard app will not differ much as the way Rails apps are usually deployed to VPS

**Comment by michelson** [comment]
Hi , I've added some articles on production deployment, one for Caprover and for digital Ocean apps, 
https://dev.chaskiq.io/en/collections/production-configuration
