### ISSUE TITLE
admin:create task missing?

### ISSUE THREAD

**Issue by ashwin47** [chaskiq/chaskiq#111]
`RAILS_ENV=development bundle exec rake admin:create`

Rake task to create new admin missing.

**Comment by michelson** [comment]
Hi , it seems so , I will fix the documentation about it

meanwhile you can use `rake db:seed`it will create an admin user

**Comment by ashwin47** [comment]
Thanks. I was able to log in.

One more thing, When I try to sign up it's making a GET request and just reloads the page. (i can see my password on the request !)

**Comment by michelson** [comment]
Hi @ashwin47 , could you send a log trace ?? I've inspected the log on my side but the password is filtered

```
Processing by Agents::CustomAuthorizationsController#create as */*
  Parameters: {"client_id"=>"h9CgouFY427ylil9EK2iLolKQZMeZVi96pTv0Q7dNhE", "client_secret"=>"[FILTERED]", "grant_type"=>"password", "password"=>"[FILTERED]", "username"=>"admin@test.com"}
 ....
Completed 200 OK in 319ms (Views: 0.6ms | ActiveRecord: 45.2ms | Allocations: 8152)
```

**Comment by ashwin47** [comment]
Its on signup. Check the [screenshots](https://imgur.com/a/8YlL14h).

**Comment by michelson** [comment]
Hi @ashwin47 , the password is displayed as `[FILTERED]`

**Comment by ashwin47** [comment]
Its displayed on the browser. Also, sign up is failing without error.

**Comment by michelson** [comment]
Hi @ashwin47 , The sign up is not implemented so we should remove the view for now. The sign_in is the only valid path and is *not* showing the password
