### ISSUE TITLE
React Native app

### ISSUE THREAD

**Issue by ericraio** [chaskiq/chaskiq#120]
Was thinking that it would be cool to have an iOS app, maybe something where you can just enter your api endpoint and access token, and the app connects to send and receive messages.

The only caveat would be push notifications

P.S.
_I love that this is open sourced and will contribute where I can._

**Comment by michelson** [comment]
It would be super cool! Anyway I've handled to make the web panel to be mobile responsive, but yeah a mobile app would be awesome. It think that for conversations & user managment will be useful. I can make a new repo and invite you, if you are interested

**Comment by ericraio** [comment]
Absolutely!

**Comment by ericraio** [comment]
Would not mind a mobile responsive web app, it's really the mobile push notifications that makes it valuable to have a native app

**Comment by michelson** [comment]
on a second thought it might be a good idea to build a chaskiq client for mobiles apps. I mean , the chat messenger window for native apps maybe a react native plugin is a good starting point.

**Comment by michelson** [comment]
I've created the repository on https://github.com/chaskiq/chaskiq-react-native and give you access 👍 I think we could get this working really soon if we replicate some of the [current window](https://github.com/chaskiq/chaskiq/blob/master/app/javascript/client_messenger/messenger.js) views & xhr calls, on the new repo. I could integrate a push notification service on the main app too.

**Comment by DavidGOrtega** [comment]
@michelson actually with react-native-web the codebase could be essentially the same.

**Comment by michelson** [comment]
@DavidGOrtega I really don't want to depend on React plugins for simple things as html views, I've rewrite the entire UI to be as lightest as possible ditching Material UI in favor of Tailwind UI for precisely that reason. 

Also , I'm not really interested in a Native application since chaskiq is a mobile friendly web app. you will not need to waste your precious cellphone space. If anyone wants to help with the development on this I will gladly help on any aspect though

**Comment by DavidGOrtega** [comment]
> I've rewrite the entire UI to be as lightest as possible ditching Material UI in favor of Tailwind UI

I don't know tailwind and why should be lightest than Material UI.

>  I'm not really interested in a Native application since chaskiq is a mobile friendly web app. you will not need to waste your precious cellphone space.

Performance can not be compared and an app of this type should not be very big.

Said that I was just only giving some advices that I have given to myself.
I actually use  [elastic ui](https://github.com/elastic/eui) and react-native-web a lot.

I highly recommend it

**Comment by michelson** [comment]
> Performance can not be compared and an app of this type should not be very big.
it's big :D but don't know what that means with regard on RN app size

if you want to give this a spin we could work on a limited version on the react-native repository though

best

**Comment by michelson** [comment]
one of the reasons of the port from material-ui which is very similar to elastic-ui (which looks good!) is that many of the components are already implemented in the code base and are made in pure html (react) and the utility css framework tailwind ui, some of those implementations are encapsulated into components but there is no magic but css https://tailwindcss.com/ 

This way will be easy for others to build new sections or components that are not tied to other frameworks and if we want to build ruby based views we will be able to use the same css utilities without React involved

**Comment by a7medo778** [comment]
hey guys, so how is the progress

**Comment by michelson** [comment]
not very much. indeed I think at this point we don't really need a native app for chaskiq

**Comment by cortopy** [comment]
@michelson has your view about not needing a mobile app changed at all? I'm currently reviewing options and mobile app is a must. This is because unless you are glued to a computer or actively staring at your phone, you won't get notifications that there's a new customer asking a question

Mobile apps are needed because of the lack of support in Android and iOS for server send events and websockets (for battery usage reasons)

**Comment by michelson** [comment]
Hi, I was working on a native app prototype, but it is far to be productionable. We use slack integration to workaround this and is working great!

**Comment by cortopy** [comment]
That sounds like a clever way to go round it. Unfortunately in my case, the main reason to go for a self-hosted customer management platform is data sovereignty. Using slack would defeat the purpose. Other than that, chaskiq looks awesome though!

**Comment by useEffects** [comment]
any update on this?
