### ISSUE TITLE
Deploying Chaskiq on Subdomain

### ISSUE THREAD

**Issue by ericraio** [chaskiq/chaskiq#122]
Currently, the routing constraints catches all subdomains and assumes to route to the knowledge base.

`constraints(SubdomainOrDomain) do`

However, this prevents deploying chaskiq on a subdomain. 

Example: For my software,  I am deploying to `https://chaskiq.xxxx.com` and `https://help.xxxx.com`

One solution could be a to leverage an environment variable to set the APP_SUBDOMAINS array in config/initializers/app_subdomains.rb

**Comment by michelson** [comment]
Hi Eric,  there is a whitelisted subdomain list that skip the contraints,
maybe we could set this as a env variable . Or add the env[HOST] to that
list.

**Comment by michelson** [comment]
the master branch now will take you ENV['HOST'] url and add the subdomain to the whitelist
