### ISSUE TITLE
rake admin:create

### ISSUE THREAD

**Issue by forever-sumit** [chaskiq/chaskiq#139]
As per the Ubuntu setup doc when run the following command 

`RAILS_ENV=development bundle exec rake admin:create`

Its giving error

```
rake aborted!
Don't know how to build task 'admin:create' (See the list of available tasks with `rake --tasks`)
Did you mean?  db:create

```

**Comment by michelson** [comment]
the new command is `bundle exec rake admin_generator`

**Comment by aalinasusan** [comment]
Run this command in console
`rails admin_generator`

The rails admin_generator task will create an admin user for you, you will need to have an ADMIN_EMAIL and ADMIN_PASSWORD on your .env
