### ISSUE TITLE
case-sensitive paths on a case-insensitive

### ISSUE THREAD

**Issue by DavidGOrtega** [chaskiq/chaskiq#150]
There are two files with the same name for a case-insensitive OS:

```
'app/javascript/src/components/SelectMenu.js'
 'app/javascript/src/components/selectMenu.js'
```

Im using MacOS

**Comment by michelson** [comment]
fixed

**Comment by mattes3** [comment]
No, it is still there! See https://github.com/chaskiq/chaskiq/tree/master/app/javascript/src/components
