### ISSUE TITLE
Heroku easy install its not that easy

### ISSUE THREAD

**Issue by DavidGOrtega** [chaskiq/chaskiq#152]
Easy heroku install is asking for many required ENV VARS that I don't know nothing about nor described in the docs.

I'm close to quit. Have tried many ways just to setup an environment and see whats going on here but none of them worked.

**Comment by michelson** [comment]
Hi, the env vars has a descripcion on every field , this are the variables:


    "SECRET_TOKEN" "A secret key for verifying the integrity of signed cookies.",
    "RACK_ENV": "Environment for rack middleware.",
    "RAILS_ENV": "Environment for rails middleware.",
    "HOST": "App's internet entry point ie:. https://domain.com",
    "WS": "App's websocket server, wss:://domain.com/cable",
    "ASSET_HOST": "App assets's internet entry point ie:. https://domain.com/",
    "SNS_CONFIGURATION_SET": "Amazon's SNS configuration set (for incoming email processing)",
    "SES_ADDRESS": "description": "Amazon's SES mail address",
    "SES_USER_NAME":  "description": "Amazon's SES mail username",
    "SES_PASSWORD": "Amazon's SES mail password",
    "AWS_ACCESS_KEY_ID": Amazon's S3 file storage key",
    "AWS_SECRET_ACCESS_KEY":  "Amazon's S3 file secret access key",
    "AWS_S3_BUCKET":  "Amazon's S3 file storage bucket",
    "AWS_S3_REGION": Amazon's S3 file storage region"

can you describe what setup did you tried in order to get more context on it?

**Comment by DavidGOrtega** [comment]
```
"HOST": "App's internet entry point ie:. https://domain.com",
"WS": "App's websocket server, wss:://domain.com/cable",
"ASSET_HOST": "App assets's internet entry point ie:. https://domain.com/",
```
could them be relative?

```
"SECRET_TOKEN" "A secret key for verifying the integrity of signed cookies.",
```
could be anything? Is there any consideration?

```
"RACK_ENV": "Environment for rack middleware.",
"RAILS_ENV": "Environment for rails middleware.",
```
Im not a ruby developer, are these some kind of common vars? what are their possible values?

```
"SNS_CONFIGURATION_SET": "Amazon's SNS configuration set (for incoming email processing)",
"SES_ADDRESS": "description": "Amazon's SES mail address",
"SES_USER_NAME":  "description": "Amazon's SES mail username",
"SES_PASSWORD": "Amazon's SES mail password",
"AWS_ACCESS_KEY_ID": Amazon's S3 file storage key",
"AWS_SECRET_ACCESS_KEY":  "Amazon's S3 file secret access key",
"AWS_S3_BUCKET":  "Amazon's S3 file storage bucket",
"AWS_S3_REGION": Amazon's S3 file storage region"
``` 
Are we enforced to use AWS? why the project can run locally without these?

**Comment by michelson** [comment]
Hi David

check this article , https://dev.chaskiq.io/en/articles/installation-on-mac

in development the only env vars you need are ones


HOST=http://localhost:3000
ASSET_HOST=http://localhost:3000
WS=ws://localhost:3000/cable
ADMIN_EMAIL=your@email.com
ADMIN_PASSWORD=123456


in production environment , for now, you will be enforced to use AWS for
assets storage & email reception

best

**Comment by DavidGOrtega** [comment]
> in production environment , for now, you will be enforced to use AWS for
assets storage & email reception

Why? without having to look into source code, why would not I be able to deploy everything with docker in one machine or even swarm (not speaking about load balancing or performance here)?
Would not the assets be saved? 
The thing is that having to setup an AWS account additionally to setup the app fast might end up in an entry barrier.

> :eyes:  I think that this information should be displayed.

Also:
> check this article , https://dev.chaskiq.io/en/articles/installation-on-mac

Still don't know what 

```
"RACK_ENV": "Environment for rack middleware.",
"RAILS_ENV": "Environment for rails middleware.",
```

are meant for and possible values.

I would focus in Github README.md for now as docs, I would make them very easy and just having one page you have a big chance to read all. If I don't have a mac (indeed I have and I opened a ticket) I can miss valuable information.

Thanks!

**Comment by michelson** [comment]
Heroku does not have a filesystem so an storage service is necessary, that's why

for production applications use "production" as RACK_ENV / RAILS_ENV

**Comment by DavidGOrtega** [comment]
> Heroku does not have a filesystem so an storage service is necessary, that's why

So i would be able to deploy in my own machine with docker?

**Comment by michelson** [comment]
> So i would be able to deploy in my own machine with docker? 

you mean deploy on any VPS ? 

anyway, chaskiq in production will use storage providers like AWS, in the future we will use others, but not filesystem for production ever

**Comment by DavidGOrtega** [comment]
> you mean deploy on any VPS ?

I was thinking more in a docker swarm cluster with gluster. So its possible then! good!

**Comment by DavidGOrtega** [comment]
> chaskiq in production

When you speak about chaskiq in production is about chaskiq as SAAS?
