### ISSUE TITLE
Dockerfile seems to be missing webpack-dev-server

### ISSUE THREAD

**Issue by DavidGOrtega** [chaskiq/chaskiq#153]
```
webpacker_1  | yarn run v1.13.0
webpacker_1  | error Command "webpack-dev-server" not found.
webpacker_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
chaskiq_webpacker_1 exited with code 1
```

**Comment by michelson** [comment]
Hi I've updated the docker for development docs at https://dev.chaskiq.io/en/articles/docker-for-development

you may run a yarn install if there is no js dependences

let me know how it goes

**Comment by michelson** [comment]
you have to git pull from master

**Comment by DavidGOrtega** [comment]
> let me know how it goes

I will! 😉 

> you may run a yarn install if there is no js dependences

Not sure what does this mean.

🤞

**Comment by michelson** [comment]
Hi , yarn is the dependency manager , so, in order to build the assets you
may need to run that command to download the dependencies first

**Comment by DavidGOrtega** [comment]
I know yarn! Im quite seasoned in JS, but Im not expecting to do it on my own but the Dockerfile

**Comment by michelson** [comment]
I think you can handle that for now, it's just a one time command. 
Otherwise, if you are really uncomfortable with that, you are welcome to contribute with an improvement on the Dockerfile

thanks!
