### ISSUE TITLE
Could not locate Gemfile or .bundle/ directory

### ISSUE THREAD

**Issue by roshanjonah** [chaskiq/chaskiq#156]
Trying to get rails up and running as per the article in documentation - https://evilmartians.com/chronicles/ruby-on-whales-docker-for-ruby-rails-development

xxx@chaskiq-srv1:~/chaskiq$ sudo docker-compose run --service-port rails
Starting chaskiq_redis_1 ... done
Starting chaskiq_postgres_1 ... done
Could not locate Gemfile or .bundle/ directory

Getting that error

**Comment by michelson** [comment]
updated instructions for docker-compose at https://dev.chaskiq.io/en/articles/docker-for-development , it's tested & working. you may need to pull from git master.
 reopen if you encounter issues, 
regards mate!
