### ISSUE TITLE
Images seems to be broken in docs

### ISSUE THREAD

**Issue by DavidGOrtega** [chaskiq/chaskiq#157]
Every single image is missing

![image](https://user-images.githubusercontent.com/414967/82187423-abc8f880-98ec-11ea-8f70-0e4a05c4ed51.png)

**Comment by michelson** [comment]
hey @DavidGOrtega ! yeah last night we migrated our app from heroku to digital ocean and we changed the RAILS_SECRET_BASE en var on the rails configuration key, this produced a 404 on every upload image with activeStorage library! this one was tricky to find https://twitter.com/Chaskiqapp/status/1262558110331396104

thanks for report this!
