### ISSUE TITLE
Empty TranslatedMessenger?

### ISSUE THREAD

**Issue by therealcos** [chaskiq/chaskiq#163]
Maybe this is a total noob question, but I just set up Chaskiq on heroku and tested it out by pasting the code snippet on a separate site of mine - everything loads fine but it just seems to be empty.  Here's is what I end up with on my page after the JS loads...

```
<div id="ChaskiqMessengerRoot">
   <div class="css-fh7lak"></div>
   <div id="TourManager"></div>
</div>
```

Am I missing something?  Is there some other setup I need to do or something else I did wrong somewhere that might be causing this?

**Comment by michelson** [comment]
Hi @therealcos , you have to configure the messenger widget to be available on the url of your site. You may have to do 2 things then, go to your app settings 
1) app settings tab: set the domain url field
2) app settings -> appearance tab: check the Activate messenger option.

let me know if that helps you

**Comment by therealcos** [comment]
You’re a saint! The Activate messenger option did it. Thanks so much! :)
