### ISSUE TITLE
Sign In Issues

### ISSUE THREAD

**Issue by therealcos** [chaskiq/chaskiq#166]
First off, I failed to say this in my last issue but I just wanted to congratulate you on a great product!  So far I'm super impressed with Chaskiq and everything it does.

Now, onto the issue(s) at hand... when I enter an incorrect email/password combo on the login screen, I see a little flicker of the dashboard first before I get an error and get sent back to the login screen.  Is there any way to prevent this (and just keep the user on the login screen)?  Related, I'm getting a 500 and general error message every time I enter a wrong email/password instead of a 401 or something more specific - should this be happening? Would this be related to the flicker?

A second unrelated question I have is about roles and if there's anything non-admin agents should be prevented from seeing. Right now when I sign in as a non-admin, I'm not able to create new apps or see a list of them, but I am able to do things like change the app's settings.  Should this be happening?  If so, and if I wanted to change this, do you have any recommendations on how to proceed with what exists already in Chaskiq?  Or should I look into adding something like Pundit for this for my own needs?

**Comment by michelson** [comment]
hey thanks for your comment, last night I've had merged a fix on that. can you checkout the master branch and try again ?

**Comment by therealcos** [comment]
That last commit fixed everything!  I'm still kind of curious about how roles work, though - are there any differences in permissions between admin and non-admin agents?

**Comment by michelson** [comment]
Hi Alex, there are no roles implemented right now so all agents are the same. This sound like a good feature though

**Comment by michelson** [comment]
there is a role model which associates the agent with the account, so we have to implement the permisions/visibility part

**Comment by therealcos** [comment]
this might be related, but i'm also getting a 500 when i hit `/agents/invitation.json` with a `password` and `password_confirmation` when accepting an invitation

**Comment by michelson** [comment]
Hi @therealcos  I've fixed the behavior, and also added a resend invitation feature. please checkout from master.

let me know how it goes

**Comment by michelson** [comment]
recover password workflows added too!

I will close this now as is solved. feel free to reopen if you find any issues related with this one
