### ISSUE TITLE
Cannot send media only from admin

### ISSUE THREAD

**Issue by deezburgers** [chaskiq/chaskiq#174]
When I try to send a photo/video to a conversation as an agent, the send button is disabled unless there is some text in the field too.  Can this be fixed to allow sending only a photo/video in a message?

**Comment by michelson** [comment]
for now the workaround is to set a caption text and send . I will keep this open till we fix this

**Comment by michelson** [comment]
fixed

**Comment by deezburgers** [comment]
I'm still noticing this issue but maybe I just missed the fix - can you point me to where in the code it is?

**Comment by michelson** [comment]
Did you updated your code with the master branch?

**Comment by therealcos** [comment]
Yes, but I think maybe I lost the fix in a merge - what file was it in?

**Comment by deezburgers** [comment]
Yes, but I think maybe I lost the fix in a merge - what file was it in?
