### ISSUE TITLE
Dependencies in Ubuntu install script don't work

### ISSUE THREAD

**Issue by wayneoutthere** [chaskiq/chaskiq#192]
Hey there. Nice project! I'm super hopeful here...  I love that this is *fully open*.  

I tried to install on Ubuntu droplet on Digital Ocean and ran into this when running the first script from [here](https://dev.chaskiq.io/en/articles/install-chaskiq-on-ubuntu-for-development) 

`bash <(wget -qO- https://raw.githubusercontent.com/techAPJ/install-rails/master/linux)`

failure was this:

```
Installing Ruby 2.7.1 ...

/home/sysadmin/.rbenv/bin/rbenv: line 49: cd: /root: Permission denied
failed
```
Hope this helps because I REALLY want to try and support this project somehow.  If we can get email into this hub too, wow....

**Comment by michelson** [comment]
Hi @wayneoutthere , maybe this answer on SO might help you https://stackoverflow.com/questions/9951043/rbenv-permission-denied 

please let me know how ti goes

**Comment by wayneoutthere** [comment]
hey there @michelson .  thanks for quick reply!  Actually i was testing out a competing 'solution' this morning which had a 'similar' issue and the problem was very simple: not enough RAM!  I had a few 1GB droplets setup for testing these (I'm learning some development but pretty bad still...) and I upgraded to 2GB on the other platform and the install started working.  I thought I would test the same theory here.  So far, it has not failed.  It is 'stuck' at the 'installing ruby' phase, but not failed.  I will confirm if this solves it when I'm done.  I would recommend, if this solves it, to put a clear message 'minimum hardware requirements 2GB' or whatever on [this page](https://dev.chaskiq.io/en/articles/install-chaskiq-on-ubuntu-for-development). Also, on this page (Sorry to put multiple things in one post) 'regular user' was not correct, i think.  I used 'root user' and the script started working.  "regular user' to me means 'non-admin' user?  Anyways, just pointing this out to help.

**Comment by michelson** [comment]
if you want to test this out why not give Heroku a try ? we have a **deploy to heroku** button on the readme

**Comment by wayneoutthere** [comment]
i went to github repository and read the readme but didn't see anything baout heroku.  I actually don't even know what heroku is but glad to learn :)

note... it seems I DO need 'regular user' for installing because when I hit `bundle install` it needs non-sudo user it seems :(  must try again process I think.

**Comment by michelson** [comment]
Hi @wayneoutthere check the readme , there is a purple button that says deploy to heroku

**Comment by augrayvr** [comment]
Hi,
 I am getting this error "sidekiq_1    | Could not find truemail-2.4.7, shoulda-4.0.0, shoulda-matchers-4.5.1," but gem both package with same version installed. Any other way to fix this issue ?

Thanks,
