### ISSUE TITLE
Unable to log in for the very First Time

### ISSUE THREAD

**Issue by moeezsaiyam** [chaskiq/chaskiq#196]
Hi, I've deployed this product to Heroku. I have set the ADMIN_EMAIL and ADMIN_PASSWORD in the .env file and also I run db:seed command but I'm unable to log in to the platform. Can anyone help regarding this?

**Comment by michelson** [comment]
the env vars in Heroku has to be set in the heroku platform, I know you have this woking because I've fixed on your heroku instance 😄
