### ISSUE TITLE
API Doc/Production Instalation Multi Organization

### ISSUE THREAD

**Issue by starl1n** [chaskiq/chaskiq#211]
Hi ,

This is not exactly an issue, but didn't know where to write about it.

First of all I love everything i see from this solution and would like to integrate it with my solution.

Have a couple of questions
1. Does Chaskiq support multiple teams? like Slack  or Mattermost where you can create a team assign, different users to a single deployment?
2. Where can I find the API documentation, feels that I only can see partial API doc
3. Where can I find a more detailed production deployment instruction (not heroku), deployment to linux or windows 

Thanks in advance

**Comment by michelson** [comment]
Hi @starl1n , thanks for writing
1. what will be the use case for groups , can you expand more ? chaskiq does not have groups, we have some permission roles right now, but maybe not what you want.
2. The API is partially documented as is an autogenerated documentation from schema I have to add some descriptions to it, but overall is really easy to explore it
3. right now I've not documented the deployment on production but we have the docker file for production in the and we have actually running on production though with k8s

**Comment by starl1n** [comment]
Thank you for the fast answer @michelson 
1. Have a web app (ERP like) where the user can create multiple organizations /teams, those teams are like different companies, what I would like to see if possible with one deployment of Chaskiq (one server) generate different embed code that can be assigned to each of the teams
2.  Copy
3. Will give a look, thanks

**Comment by michelson** [comment]
Hi @starl1n , well , in chaskiq you have apps, so you could have multiple apps in one chaskiq server instance
so, one user can have multple apps with multiple users , does make sense to you ?
