### ISSUE TITLE
GUIDE FOR AWS 

### ISSUE THREAD

**Issue by besoeasy** [chaskiq/chaskiq#213]
AWS S3 don't have region -> what should users use ?

why not a alternative for AWS SES such as SMTP ?

Can the core developers atlteast make a small video explaining the aws variables and setup

**Comment by michelson** [comment]
AWS S3 does have region, usually is `us-east-1` but you have to check that in your aws console
for email config you could change the production.rb settings , check the commented code on SMTP that I've pointed in #212

**Comment by besoeasy** [comment]
hey man, it would be nice to have a video demo 🎉🎉

so that we could be able to help new comers
