### ISSUE TITLE
does it work with users that are not "logged on"?

### ISSUE THREAD

**Issue by jtorjo** [chaskiq/chaskiq#215]
Basically, I'd like to identify a user by a unique ID that I compute (like, a computer fingerprint), and be able to talk to him this way (my customer support should be able to talk to him over the course of several days)

Would this be possible with chaskiq?

**Comment by michelson** [comment]
this can be accomplished by registering the user by email, you can send an encrypted data that contains that indentifier.
for non registered user we identify by a cookie, but if the user remove cookies, or visits on different browser or machine, they will not be identified

**Comment by michelson** [comment]
so , if you have your user loggedin in your system you can identify them

**Comment by jtorjo** [comment]
> for non registered user we identify by a cookie, but if the user remove cookies, or visits on different browser or machine, they will not be identified

That makes sense. The thing that I want to accomplish is allow the user to send me feedback without any friction (without the requirement to login). So basically as I can uniquely identify the user, I'm ok  - I just want to receive his/her feedback, and have a conversation. 

The possibility of the user deleting cookies is very unlikely, but yeah it's possible.

> this can be accomplished by registering the user by email, you can send an encrypted data that contains that indentifier.

is it possible to somehow open the page and specify at load the user's ID? (my initial question)

**Comment by michelson** [comment]
yes you set the user details on page load

**Comment by jtorjo** [comment]
awesome, thanks!
