### ISSUE TITLE
Update Ruby version in .ruby-version file

### ISSUE THREAD

**Issue by lporras** [chaskiq/chaskiq#232]
Hi @michelson,

I'm following the article [Installation on Mac for Development](https://dev.chaskiq.io/en/articles/installation-on-mac) and it says to run this [script](https://github.com/techAPJ/install-rails/blob/master/mac) first.

So I saw that running that [script](https://github.com/techAPJ/install-rails/blob/master/mac) will install the latest stable version of Ruby in my system and it would be 2.7.1.

<img width="799" alt="Screen Shot 2020-10-01 at 06 49 35" src="https://user-images.githubusercontent.com/232293/94794879-e66e9180-03b2-11eb-93b5-27a5f4c6e6a5.png">

But when I cloned Chaskiq and open the folder on my terminal then RVM (Sorry I'm not using Rbenv 🤦🏽 ) detects the file .ruby-version and it says this message:

<img width="305" alt="Screen Shot 2020-10-01 at 06 57 07" src="https://user-images.githubusercontent.com/232293/94795148-567d1780-03b3-11eb-9731-39a82c156c29.png">

So I think we should upgrade this file to contains ruby version ```2.7.1```

¿What do you think?  ¿Do you want me to add this change?

Thanks

**Comment by michelson** [comment]
upgraded to 2.7.1  , thanks!
