### ISSUE TITLE
Not delivering sessions due to an invalid api_key

### ISSUE THREAD

**Issue by hverma95** [chaskiq/chaskiq#251]
Hi,

I have been trying to configure the chaskiq application.

After starting the server the web page is blank and it throws the following error:

$bundle exec rails server

=> Booting Puma
=> Rails 6.0.3.2 application starting in development 
=> Run `rails server --help` for more startup options
Puma starting in single mode...
* Version 5.0.4 (ruby 2.7.1-p83), codename: Spoony Bard
* Min threads: 5, max threads: 5
* Environment: development
* Listening on http://127.0.0.1:3000
* Listening on http://[::1]:3000
Use Ctrl-C to stop
Started GET "/" for ::1 at 2020-11-08 03:04:23 +0530
   (1.2ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by HomeController#show as */*
  Rendering home/show.erb within layouts/application
  Rendered home/show.erb within layouts/application (Duration: 1.8ms | Allocations: 300)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 8673ms (Views: 8659.5ms | ActiveRecord: 0.0ms | Allocations: 10111664)

**Not delivering sessions due to an invalid api_key**

**Comment by michelson** [comment]
Hi @hverma95 , that's just Bugsnag gem saying that it will not send data to their service. 
of course if you add your bugnag api key it will, it's just a warning that you could skip safely

thanks for report

**Comment by hverma95** [comment]
Hi @michelson ,

Thanks for the information. But how can I add the bugsnag key and where can I find the same.

Also if it is just a warning, it should load the web page at least. But it is not loading for some reason.

So please provide the above details.

Your response is much appreciated.

**Comment by dorianmariecom** [comment]
If you are testing locally and don't need to connect to bugsnag, you can do:

```ruby
# Gemfile
gem "bugsnag", require: false
# config/initializers/bugsnag.rb
if ENV["BUGSNAG_API_KEY"]
  require "bugsnag"
  Bugsnag.configure { |config| config.api_key = ENV.fetch("BUGSNAG_API_KEY") }
end
```

**Comment by garmoshka-mo** [comment]
Unfortunately, Bugsnag gem is buggy and still works even when key is not provided. But if you will not require gem - code will become broken, e.g. bugsnag's controller hooks, etc..

You can disable output in dev mode following way:

```
if ENV['BUGSNAG_KEY'].present?

  Bugsnag.configure do |config|
     ....
  end

else

  Bugsnag.configuration.logger = ::Logger.new("/dev/null")

end

```
