### ISSUE TITLE
"Invalid Grant" 400 error on first login in development (after following instructions for Mac OSX)

### ISSUE THREAD

**Issue by timcowlishaw** [chaskiq/chaskiq#255]
Hey folks!

I'm sure this is something i'm doing wrong, but, after following the [instructions for development setup on Mac OS X](https://dev.chaskiq.io/en/articles/installation-on-mac) to the letter, when i go to log in on the development server, `http://localhost:3000/oauth/token.json` returns a 400, with the message: `{"error":"invalid_grant","error_description":"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."}`. All the specs pass, and I can't find any further details in the logs, and am at a complete loss, basically. Inspecting my newly created admin user from the console suggests that it should be authorized to login:

```
irb(main):017:0> agent.valid_for_authentication? { agent.valid_password?("password" ) }
=> true
```

Some googling around this error message from doorkeeper suggests the problem might be the (lack of) a `callback_url` sent with the authorization request (the parameters sent to `oauth/token.json` are `{"agent":{"email":"admin@example.com","password":"password"},"email":"admin@example.com","password":"password","grant_type":"password"}`) - but i can't find any indication of where this callback_url would be set, or what it should be, so possible that's a red herring?

Any information you could provide would be gratefully received, Chaskiq looks like  a great project and ideal for our purposes if i can get it up and running!

Thanks,

Tim

**Comment by timcowlishaw** [comment]
Sorry folks, this turns out to have been a massively stupid error on my part - turns out i was running `rails server` with `RAILS_ENV=test`. I am appropriately embarrased and will close this issue.

**Comment by michelson** [comment]
no problem Tim, glad to see you solve it 👍
