### ISSUE TITLE
Messenger not showing on page

### ISSUE THREAD

**Issue by tabrza** [chaskiq/chaskiq#277]
Good day, 
I installed chaskiq successfully on heroku. However, when I insert the script into the bottom of my body tag on my [website](https://ezdealsapp.com/), it doesn't show on the page.  The chaskiqmessengerroot div does show on the elements console though.. Is there anything I may have missed in the setup?

**Comment by michelson** [comment]
Hi there, check the app settings in the chaskiq panel, in the `domain url` field you have to add your website domain, also you will need to activate messenger checkbox in the same settings section

**Comment by tabrza** [comment]
That did the trick. thank you!

**Comment by tabrza** [comment]
@michelson Is there a way to turn off or edit the initial are you a customer message?

**Comment by michelson** [comment]
@tabrza yes, check this option

![image](https://user-images.githubusercontent.com/11976/105849890-c432fc00-5fbf-11eb-9c7a-8dfb02715358.png)

**Comment by tabrza** [comment]
Wonderful, loving the app already. Thanks so much. 
@michelson  - whenever time allows, would be great to have some insights into how to setup the app for different types of campaigns, routings, downloading conversation data with tags, assigning conversations to a team instead of a user etc. 
I'll be putting together a doc as well as I start discovering this and will share when possible
