### ISSUE TITLE
floating box

### ISSUE THREAD

**Issue by tabrza** [chaskiq/chaskiq#280]
is there a way to initiate the conversation when the user lands on a site/trigger a bot depending on which page they are? kind of like with floating chat bubbles (currently is a floating box in chaskiq)
![image](https://user-images.githubusercontent.com/21217850/106231476-a1008a80-6213-11eb-85da-093ef8c9ece7.png)

**Comment by michelson** [comment]
yes, we have that, check the option on messenger settings and you are done

![image](https://user-images.githubusercontent.com/11976/106276017-9fd05d00-6215-11eb-8429-04f750557dfc.png)

feel free to reopen if you have more questions

**Comment by tabrza** [comment]
@michelson , yes thanks i saw that! I wanted to know if it was possible to have a prompt message sent to the user from the bot before the user sends a message in the widget? in this way, the user would be encouraged to interact with the widget/agent. 
additionally, is it possible to have different prompt messages sent to the user dependent on the page they are on?

**Comment by michelson** [comment]
yes, you can use the task bots for that. so you can automate the segment of users and define the conversational paths for that

**Comment by tabrza** [comment]
hi @michelson - thanks so much for your help till now. have several more questions coming your way.. apologies 

1. how does the help center setup work
2. what does hidden constraints mean in campaigns?
3. how do mailing campaigns work?
4. how do in app message campaigns work? would banners appear on the widget? how do we trigger them?
5. When creating rules, and adding filters, the 'missing value' filter appears. How does that work?
6. how can a bot be triggered to send a message to the user as soon as they land on the website instead of the user needing to send an initial message to the widget?
7. how do assignment rules work? is it possible to assign teams to conversations instead of single users in assignment rules/bot handover?
8. conversation number doesn't show correctly.. how are they filtered? even including open/closed 
9. is it possible to highlight the tab or something like with fb messenger to show a new chat or number of chats available in order to avoid missed chat? 
10. How can whatsapp be connected so that messages are sent to a whatsapp business account?
11.  How can slack be integrated?
12. Unable to upload logo/user image. Don't get an error in the heroku console either.. Have you encountered this issue before?
13. With always ask user for email address before starting conversation, it does not require this on the front end. is it possible to do this wiht a phone number as an alternative?
14. in the bot section, ask for contact details if the app doesn't have the email address or phone number doesn't exist only works in default behaviour
15. unable to uncheck: Leave a 2 minute delay before triggering Task Bots during office hours button under for users tab

**Comment by tabrza** [comment]
hi @michelson  - please do get back to me on the above when you can. Hoping to take this live towards the end of the week!
