### ISSUE TITLE
VM Server Installation Live Chat： NoMethodError in ArticlesController#show

### ISSUE THREAD

**Issue by ilovebamboo** [chaskiq/chaskiq#281]
![image](https://user-images.githubusercontent.com/6214084/106379066-6d288f00-63e4-11eb-9d39-7094ac2a2c32.png)
http://chat.appx.vip
hello,devloper
how to do?
i don’t find 80 http,
i used nginx proxy port forward 127.0.0.1:3000

![image](https://user-images.githubusercontent.com/6214084/106386155-9e1db980-640e-11eb-834e-44294e224178.png)

I want to use a virtual server to install ,I want the features in the picture, what should I do?

**Comment by michelson** [comment]
You must to set the env vars for HOST and WS to point to your domain, it's all documented on dev.chaskiq.io

**Comment by APPX-Studio** [comment]
I don't know how to configure it, I found the docker instructions without the port
