### ISSUE TITLE
FATAL: database "chaskiq_dev" does not exist

### ISSUE THREAD

**Issue by APPX-Studio** [chaskiq/chaskiq#294]
![image](https://user-images.githubusercontent.com/49307767/108142332-8a599f00-7100-11eb-9384-821df96218d0.png)

**Comment by APPX-Studio** [comment]
![image](https://user-images.githubusercontent.com/49307767/108484377-baf33180-72d6-11eb-8352-0ad3b23e6028.png)

**Comment by APPX-Studio** [comment]
![image](https://user-images.githubusercontent.com/49307767/108510854-010dbc80-72fa-11eb-9d46-07a3081fb485.png)

**Comment by michelson** [comment]
in the docker command try to change rake for rails , so it's `docker-compose run rails rails db:...`
