### ISSUE TITLE
Webpacker::Manifest::MissingEntryError in Home#show

### ISSUE THREAD

**Issue by APPX-Studio** [chaskiq/chaskiq#297]
![image](https://user-images.githubusercontent.com/49307767/108575413-1f54d600-7355-11eb-8a46-bf3f61b970f6.png)
What's the problem? What's next?

**Comment by michelson** [comment]
I would say you are missing the `yarn install` step, after that , exec `yarn dev` on a new terminal tab

**Comment by APPX-Studio** [comment]
> I would say you are missing the `yarn install` step, after that , exec `yarn dev` on a new terminal tab

thank you , i have install. 
I don't find admin dashboard page.
Now it shows no content


![image](https://user-images.githubusercontent.com/49307767/108591596-8057ca80-73a4-11eb-9321-97bd8ddba364.png)

Why is my installation different from this image?
![image](https://user-images.githubusercontent.com/49307767/108591445-ca8c7c00-73a3-11eb-8ad4-f2937bc6e402.png)

**Comment by michelson** [comment]
you probably don't have environment variables set for HOST? but is hard to tell by the screenshot. you might need to see the browser console if there is any errors and the rails console too.
