### ISSUE TITLE
Build new image -

### ISSUE THREAD

**Issue by acardozzo** [chaskiq/chaskiq#305]
Hi there, I know u already have an image available in docker hub and that is awesome, but I need to insert a new locale. Before start i tried to build a new image from the code but I got some erros. The process seems to be the basic in the docker, so I did that considering the existent Dockerfile and the command:
docker build --build-arg APP_ENV=production \
             --build-arg RUBY_VERSION=2.7.1 \
             --build-arg PG_MAJOR=11 \
             --build-arg NODE_MAJOR=12 \
             --build-arg YARN_VERSION=1.13.0 \
             --build-arg BUNDLER_VERSION=2.1.3 \
             -t chaskiq \
             .

*****************

And for some reason that I don't know why I got this:

#23 756.0
#23 756.0 Browserslist: caniuse-lite is outdated. Please run the following command: `npx browserslist --update-db`
#23 756.0
#23 756.0 warn - Tailwind is not purging unused styles because no template paths have been provided.
#23 756.0 warn - If you have manually configured PurgeCSS outside of Tailwind or are deliberately not removing unused styles, set `purge: false` in your Tailwind config file to silence this warning.
#23 756.0 warn - https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css
#23 756.0
------
executor failed running [/bin/sh -c NODE_ENV=${APP_ENV} NODE_OPTIONS="--max-old-space-size=2048"     SECRET_KEY_BASE=`bin/rake secret` RAILS_ENV=${APP_ENV}     bundle exec rails assets:precompile     && rm -rf /usr/src/app/node_modules /usr/src/app/tmp/cache/* /tmp/*     && yarn cache clean]: exit code: 1

Did u got something different when u build the default image? Is there anything that I need to do additionally?

I appreciate your help.

**Comment by michelson** [comment]
the docker for development works for you ? try docker-compose build

also, I will be glad to extend the languages just create a pull request

**Comment by acardozzo** [comment]
Really?   I really appreciate that. I need pt-BR.  Docker-compose works fine. But build production not.  I wanna also contribute to write a instruction to use aws ECS. can I help with that? I will setup on my side and write the instruction.

**Comment by michelson** [comment]
yeah if it works for you on development try a pull request with the new language and I will help there. then the PR could be merged on the oficial image, will be great to have Brasilian portuguese language.

the current image chaskiq:latest works for you on ECS ? did you see the docker guides on dev.chaskiq.io ?

for the ECS documentation please feel free to contribute on that too

best

**Comment by acardozzo** [comment]
I didn't tested yet on ECS. But based on the other instruction I understood we have mainly two containers both uses same image but with distinct functions. One container handle the communications and the other acts as worker, that only communicate with database. Both depends on Postgre and Redis up and running. And whole project startup based on env data if that exists. Am I Right?. Based on that we have everything to work with ECS. I will try that today and let u know. About the translation I will translate the yaml.

**Comment by michelson** [comment]
Hi @acardozzo , yes, it's the same image , with the same ENV vars. and yes the web instance serves the app and the worker process heavy tasks. both depends on the same data. it's just the same app that's is loaded on web & worker.

**Comment by acardozzo** [comment]
SECRET_KEY_BASE is optional. isn't it?
