### ISSUE TITLE
undefined method `app' for nil:NilClass

### ISSUE THREAD

**Issue by Turab** [chaskiq/chaskiq#306]
I setup Chaskiq with the [preset ](https://github.com/caprover/one-click-apps/blob/master/public/v4/apps/chaskiq.yml)of Caprover; but with everything pre-set, the containers keep restarting and the UI never loads. Then I tried manual installation provided by Chaskiq [here](https://dev.chaskiq.io/en/articles/caprover-production-deployment). The console said "switching to inspect mode" without leaving any traces in error logs.

Then I tried manual installation, now for the first time I got to run the container without a reset; but this time UI gives this error:

```
undefined method `app' for nil:NilClass

def messenger_data
article_setting = ArticleSetting.find_by(subdomain: request.subdomain)
@app = article_setting.app
key = @app.encryption_key
@sessionless = params[:sessionless]
```

**Comment by michelson** [comment]
you need to setup the env variables for HOST and WS.

**Comment by Turab** [comment]
It is already set like:
![image](https://user-images.githubusercontent.com/1780719/109652855-55723100-7b71-11eb-8b8d-1f4a3436ffe9.png)

**Comment by michelson** [comment]
if you are using caprover there is also a websocket option that you have to enable on the caprover admin, look for that

**Comment by michelson** [comment]
the error tells 2 things, the app is not found, so 

did you run the rails db:seed ? did you run it after the env vars was setup ?

**Comment by Turab** [comment]
Websocket is enabled. Env vars are set before Chaskiq setup. Now I ran "rails db:seed" per your suggestion, but it's still the same. (By the way I tried many different image tags, right now the image I pulled is chaskiq/chaskiq:latest.

```
rails db:setup -e DISABLE_DATABASE_ENVIRONMENT_CHECK=1
rails db:migrate
rails db:seed
```

When I run these commands, they all succeed. But I am not sure if I need to apply all env vars here too. (I normally have them defined in Caprover interface.)

**Comment by michelson** [comment]
can you share your env vars , of course without the sensible keys

**Comment by Turab** [comment]
```
HOST=https://chaskiq.domain.com
WS=wss://chaskiq.domain.com/cable
DATABASE_URL=postgres://chaskiq:-------@srv-captain--postgresql:5432/chaskiq
RAILS_ENV=production
RAILS_LOG_TO_STDOUT=true
RAILS_SERVE_STATIC_FILES=true
REDIS_URL=redis://default:---------@srv-captain--chaskiq-redis:6379
SECRET_KEY_BASE=------------------------------------
AWS_ACCESS_KEY_ID=n
AWS_SECRET_ACCESS_KEY=n
AWS_S3_BUCKET=n
AWS_S3_REGION=n
ADMIN_EMAIL=mail@company.com
ADMIN_PASSWORD=----------
```

Right now I don't have AWS so I didn't fill them with correct information, but I guess this shouldn't prevent start up, right?

By the way for testing I also changed "RAILS_LOG_TO_STDOUT" to "false" to see if something changes in log files. And I also tried setting "RAILS_ENV" to "development" instead of "production" to see that error message in the UI.

**Comment by michelson** [comment]
ok, looks good to me, did you add the `https://chaskiq.domain.com` to the
caprover custom domain in caprover app panel ?

**Comment by Turab** [comment]
It is already the default domain that Caprover created. I mean it is not a custom domain, it is the default created domain already.

For a solution chance; is it possible to rebuild Chaskiq from source right inside the container?

**Comment by michelson** [comment]
there is probably a misconfiguration on the HOST var and the domain the app
lives , when that happens you have that error

**Comment by Turab** [comment]
You know how Caprover works;

- You specifiy a root domain like: apps.domain.com
- You create an app, here it is Chaskiq
- Caprover automatically assigns this domain to your app: chaskiq.apps.domain.com

Right now, this domain is assigned, I mean I didn't create a custom domain yet. And I set the HOST var with this value. (chaskiq.apps.domain.com)

So there is no misconfiguration in HOST var.

**Comment by michelson** [comment]
you will need to enter the image , open a bash session into it , then enter the rails console with `rails c` then check if the ENV var is readed properly ., ie: `ENV['HOST']` if is nil , there is a missconfiguration, I have seen that sometimes it coould happend that the ENV vars are not updated correctly when the pod restarts on caprover

**Comment by Turab** [comment]
I checked and HOST var is set correctly. But there is also a HOSTNAME var and it is set to a random string like "128186a5671a"

**Comment by jrxcorp** [comment]
I have a same problem.

**Comment by michelson** [comment]
it's the HOST env var that is not properly set on the machine. the HOST (and WS) domain should match the domain in which the app will be served

**Comment by jrxcorp** [comment]
HOST is correct.

NoMethodError (undefined method `app' for nil:NilClass)

**Comment by jrxcorp** [comment]
It worked, friend! It was really HOST, I was putting a new domain in the App through CapRover, but I left the default and it worked.

Thanks

**Comment by jrxcorp** [comment]
Another error:

undefined method `normalized_site` for nil:NilClass

from /api/graphql

What is?

**Comment by Turab** [comment]
I added a new domain and changed the HOST var in the app settings, now it works. It is interesting that for some people custom domain doesn't work and for me that the default domain doesn't work.

**Comment by michelson** [comment]
@Turab interesting indeed , would you mind to share here the old domain and the new one ?

**Comment by Turab** [comment]
Default one was chaskiq.apps.domain.com now I added a custom domain like support.domain.com

If you intended to ask the real domain, I can send it to you via email.

**Comment by michelson** [comment]
no worries, I'm glad that it worked finally. 
I've though that the problem could be multiple subdomains, but I've just tested some installation with https://captain.captain.chat.xx.com/ and it worked just fine. 
you could also see the caprover app logs to see if there is something there too. 
again , glad to see that you have this up & running :)
