### ISSUE TITLE
websocket not working properly in dev mode

### ISSUE THREAD

**Issue by vikash766** [chaskiq/chaskiq#307]
First of all, i would like to thanks & congratulate project contributors for this amazing work.

We have installed chaskiq in dev mode with docker, everything is working fine except web-socket is not working properly from support desk portal.

Every time we have to refresh the conversation page to get new message from messenger UI chat client. (Messages from support portal to chat client comes properly though).

We are not getting any error message to debug the issue!

It would be better if you can provide a documentation to run this app in production mode on any linux server (VPS)

our env conf file:

Please let me know how i can debug and solve this issue?

`
HOST=https://support.website.com/
ASSET_HOST=https://support.website.com/
WS=ws://support.website.com/cable

SNS_CONFIGURATION_SET=metrics

SES_ADDRESS=smtp.sendgrid.net
SES_USER_NAME=
SES_PASSWORD=

SMTP_DELIVERY_METHOD=smtp

SMTP_ADDRESS=smtp.sendgrid.net
SMTP_USERNAME=
SMTP_PASSWORD=

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=

AWS_S3_BUCKET=
AWS_S3_REGION=us-east-1

FULLCONTACT_TOKEN=

ADMIN_EMAIL=
ADMIN_PASSWORD=

DEFAULT_SENDER_EMAIL=
`

**Comment by michelson** [comment]
```
HOST=https://support.website.com/
ASSET_HOST=https://support.website.com/
WS=ws://support.website.com/cable
```

it seems you are using SSL (https) so you need to setup the WS url as `wss://support.website` ... note the `wss://`

**Comment by vikash766** [comment]
it worked....thanks a ton! @michelson
