### ISSUE TITLE
422 (Unprocessable Entity) error while trying access Chaskiq using client widget

### ISSUE THREAD

**Issue by mazharoddin** [chaskiq/chaskiq#324]
Hi,
I installed chaskiq on heroku and the installation was successful. I could able to access the test account using an admin user. 
I am trying to access the chaskiq using the client widget by adding the below JS code to the application layout file of the client(where I want to have live chat).

        (function(d,t) {
          var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
          g.src="https://xxx.herokuapp.com/embed.js"
          s.parentNode.insertBefore(g,s);
          g.onload=function(){
            new window.ChaskiqMessengerEncrypted({
              domain: 'https://xxx.herokuapp.com',
              ws:  'wss://xxx.herokuapp.com/cable',
              app_id: "xxxxSyj1foZGvGUwk3rQR",
              data: "YOUR_ENCRYPTED_JWE_DATA",
              lang: "USER_LANG_OR_DEFAULTS_TO_BROWSER_LANG" 
            })
          }
        })(document,"script");
      
But there is no messenger window is appearing( I enabled messenger using messenger settings).
In the firefox debug console  I am seeing the below js error. 

POST https://xxxx.herokuapp.com/api/graphql 422 (Unprocessable Entity)
(anonymous) @ embed.js:2
e.exports @ embed.js:2
e.exports @ embed.js:2
Promise.then (async)
s.request @ embed.js:2
i.forEach.s.<computed> @ embed.js:2
(anonymous) @ embed.js:2
send @ embed.js:2
e @ embed.js:2
g.onload @ (index):531
load (async)
(anonymous) @ (index):530
(anonymous) @ (index):539
embed.js:2 Error: Request failed with status code 422
    at e.exports (embed.js:2)
    at e.exports (embed.js:2)
    at XMLHttpRequest.p.<computed> (embed.js:2) undefined

Please let me know how I can add the messenger widget to the client rails application. Thanks.

**Comment by michelson** [comment]
Hi the 422 status is an error from chaskiq , this means that you have not configured the domain_url on your app.
to solve this go to your app settings and add the domain (or domains separated with comma) in which the chat will live

![image](https://user-images.githubusercontent.com/11976/110674765-fb94eb00-81b0-11eb-9c13-e4811385637f.png)

also you will need to "activate" the chat, in the same settings section go to messenger settings:

![image](https://user-images.githubusercontent.com/11976/110674916-1ff0c780-81b1-11eb-9c6f-3daf6b564bb9.png)

**Comment by mazharoddin** [comment]
Excellent, Now it's working. Thanks.
