### ISSUE TITLE
Graphql mutation request returns "Data not found"

### ISSUE THREAD

**Issue by CalvoM** [chaskiq/chaskiq#349]
Hello,
I built from source on Ubuntu 20.04. 
I got the graphql part working and query requests work. However whenever I make a mutation request I seem to get this response: 
```js
{
  "errors": [
    {
      "message": "Data not found",
      "data": {}
    }
  ]
}
```
Example mutation request I sent to get the response above:
```js
mutation updateAppUser($appKey: String!, $options: Json!, $id: Int!) {
  updateAppUser(appKey: $appKey, options: $options, id: $id) {
    appUser {
      id
      name
      email
    }
  }
}
```
I have the variables Query Variables as below:
```js
{
	"appKey": <My_APP_KEY>,
	"options": {
		"name": <Custom_Name>
	},
	"id": <My_ID>
}
```
Please help me know the solution to the problem.

**Comment by michelson** [comment]
Hi @CalvoM , it's hard to tell what could be happing here, the **Data not found**  is a handled error for `ActiveRecord::RecordNotFound` , so you are not getting the right record, could be a wrong id

**Comment by CalvoM** [comment]
Thanks for the hint for finding the solution. So I went through the sql logs and found I had not created a user. The id I was providing was the agent id. 
The solution was to create a user and get the user id.
