### ISSUE TITLE
Guide for Digital ocean

### ISSUE THREAD

**Issue by msamirma** [chaskiq/chaskiq#353]
Hello,

I followed the guide to deploy on digital ocean, however, I got stuck with environment variables
```
HOST: https://your.app.host.com
WS: wss://your.app.host.com/cable
```
Should I create a host first?

**Comment by michelson** [comment]
yes you will need a working host, or use the host that DO provides, note that you can deploy and add those variables after

**Comment by michelson** [comment]
also note that domains with double sub domain will not work try https://app.host.com instead of https://your.app.host.com

**Comment by msamirma** [comment]
Great will try those, Thank you

**Comment by msamirma** [comment]
Deployment completed well, but when i tried to login with admin credentials it return an "invalid_grant" : The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.
@michelson any insights or how to troubleshoot ?

**Comment by msamirma** [comment]
@michelson never mind, I managed to login with my credentials after running migrations and seed for some reason wasn't applied once deploy

**Comment by msamirma** [comment]
Hi,
I faced another issue :)
I keep getting **WebSocket connection failed**
and here's the config
`
- key: HOST
        scope: RUN_AND_BUILD_TIME
        value: https://hamamatransport-xn76s.ondigitalocean.app
      - key: WS
        scope: RUN_AND_BUILD_TIME
        value: wss://hamamatransport-xn76s.ondigitalocean.app/cable
      - key: ASSET_HOST
        scope: RUN_AND_BUILD_TIME
        value: https://hamamatransport-xn76s.ondigitalocean.app
`
Could you check please?

**Comment by roadtouk** [comment]
I am currently in this situation and can't seem to figure out how to run migration and seed as @msamirma suggested.

The do-app is deployed, but admin email and password returns that invalid grant error with status code of 400.

What can I do?

**Comment by michelson** [comment]
Hi, you need to enter to the app console tab and then run the command.

![image](https://user-images.githubusercontent.com/11976/150036755-e5f9ebca-2452-4672-a604-2a1c76ba16e0.png)

**Comment by roadtouk** [comment]
Once I run `bundle exec rails db:migrate` and `bundle exec rails db:seed`, the following happens and and I still get 400 status in in reponse to oauth/token.json

![Screenshot 2022-01-19 at 10-35-13 ruk-chat - DigitalOcean App Platform](https://user-images.githubusercontent.com/85528361/150114049-d7bac7f1-5315-4efe-894a-9dea3c3a068c.png)
