### ISSUE TITLE
is there a docker-compose  for production 

### ISSUE THREAD

**Issue by Aicha-cher** [chaskiq/chaskiq#363]
Hello all, 

Please do you have any docker-compose for production 

Thanks

**Comment by michelson** [comment]
Hi, there is no docker-compose for production, just the docker image.

**Comment by Aicha-cher** [comment]
@michelson Thanks but i really appreciate if you can help me with the following : 

-  does the docker hub image  need any dependencies ?  
- also which env  variables are needed , volume that need to be mounted, ports to be mapped , emails settings..etc

**Comment by michelson** [comment]
> @michelson Thanks but i really appreciate if you can help me with the following :
> 
> * does the docker hub image  need any dependencies ?
> * also which env  variables are needed , volume that need to be mounted, ports to be mapped , emails settings..etc

for variables check:
https://dev.chaskiq.io/en/articles/enviroment-variables-configuration

Docker image has all its dependences, you just need to connect to a redis & pg db instances (see the env vars) and run the app with these commands:
you have to run two instances : 
server: `bundle exec rails server -b 0.0.0.0 -p 3000`
worker: `bundle exec sidekiq -C config/sidekiq.yml`

**Comment by eelco2k** [comment]
Perhaps this might help:

and i created a small repo for a docker-compose in production so you can run it on own server:
[https://github.com/eelco2k/chaskiq-docker-compose](https://github.com/eelco2k/chaskiq-docker-compose)
