### ISSUE TITLE
Video chat is not working

### ISSUE THREAD

**Issue by gabrieletassoni** [chaskiq/chaskiq#365]
Hi,
I've installed chaskiq in a docker setup, the frontend widget for chatting works, messages go from frontend to backend and I can answer from the backend. But the video call does not work, from the backend, clicking on the video call feature to start one never reaches the customer on the frontend.
Are there hidden setup, port forwards or anything I must be aware of? Is the video chat feature webrtc? Maybe I have to deal (setup) with the installation of a stun/turn server I see googling around for webrtc chat?

Thank you very much for the answer.

**Comment by michelson** [comment]
Are you using a custom local domain? Webrtc will not work on non https connections unless the domain is localhost

**Comment by gabrieletassoni** [comment]
> Are you using a custom local domain? Webrtc will not work on non https connections unless the domain is localhost

Hi, thanks for the answer, I'm using a public domain in https, but I check better, thanks.

**Comment by gabrieletassoni** [comment]
Ok, tested, the key factor is to have both chaskiq backend and the website frontend served on a public url. It works automagically in that situation.
Thank you for the insight.

**Comment by michelson** [comment]
hey @gabrieletassoni , glad to hear that!
