### ISSUE TITLE
Widget configuration to show in backend Conversations the client Email or Name

### ISSUE THREAD

**Issue by gabrieletassoni** [chaskiq/chaskiq#366]
Hi, 
I'm implementing the web widget into a website, from a tutorial page, I can't find again, I understood that in the snippet here:

```javascript
        (function(d,t) {
          var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
          g.src="https://chat.deventa.io/embed.js"
          s.parentNode.insertBefore(g,s);
          g.onload=function(){
            new window.ChaskiqMessengerEncrypted({
              domain: 'https://chat.deventa.io',
              ws:  'wss://chat.deventa.io/cable',
              app_id: "RQWaCmihfArXXJcCBTtYFMsF",
              data: "YOUR_ENCRYPTED_JWE_DATA",
              lang: "USER_LANG_OR_DEFAULTS_TO_BROWSER_LANG" 
            })
          }
        })(document,"script");
```

If YOUR_ENCRYPTED_JWE_DATA is filled, on the backend side, in the conversations section, I would see the conversation with the User's Name instead of a generic `visitor KU487`, but I don't seem to find a way to create that YOUR_ENCRYPTED_JWE_DATA to achieve that.

The ruby code I use in my site's backend to generate that YOUR_ENCRYPTED_JWE_DATA is this (it's in the user's model of my backend and passed to the frontend where the widget resides using REST API):

```ruby
def jwe_data
    key = Settings.ns(:chaskiq).jwe_encryption_key
    json_payload = {
        email: email,
        properties: {
            name: fullname.presence || username,
        }
    }
    JWE.encrypt(json_payload.to_s, key, alg: 'dir')
end
```

On the frontend side, a console log shows, for the YOUR_ENCRYPTED_JWE_DATA  this:

`eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4R0NNIn0..FPJEw1o7-Q5kf4aj.o0CQxATdNdOengpArTjFJ3I-tM0BsHDrLuVwqtgc2-uRZiUdSDa4Z2Q3-aEAnvf20_ffGEJ_n3f335mf.y6zXSZm7e8l2ouzkaxxirg`

Which is the same from what I see in the log of my rails backend, but the chaskiq backend does not recognizes (decrypts?) it or anyway uses it to auto create the user with right Name and email (I would like to use this info to keep track of which users from my rails app are using the chat feature, without having to keep the users models sincronized between my rails app and the chaskiq app.

The JWE library i use is this: https://github.com/jwt/ruby-jwe

Maybe I'm not aiming at the right direction, but I feel like the `json_payload.to_s` could be the culprit, but if I use just `json_payload`, the JWE.encrypt throws an error.
Is there a working example (better) or an in depth documentation on how to create a valid YOUR_ENCRYPTED_JWE_DATA?

Thank you

**Comment by gabrieletassoni** [comment]
Also, I can't find how to disable the welcome bot, I don't want it asks things, maybe just welcome and that he will be replied soon, but no questions to the user.

**Comment by michelson** [comment]
Hi , you have to sign the encryption with your encryption key provided by chaskiq, (app-> settings -> security)

the snipped has to provide a stringified key so:

`data: "YOUR_ENCRYPTED_JWE_DATA"`, is now `data: "<%= jwe_data %>",`

also you will see in the security page that there is a new method for identify users, a simpler an more documented, but it does not encrypts

**Comment by gabrieletassoni** [comment]
I didn't see the other method, could you point me in the right direction for the documentation? Thank you. Great to know, I don't need encryption, just user identification

**Comment by michelson** [comment]
update to latest version / image

**Comment by gabrieletassoni** [comment]
Ok, I finally managed to update to the latest docker image, and I can see the documentation for the new Security application, with the inline documentation for the feature, thanks (good to have the documentation in the relevant section. I test the new way in the next few days. Now closing this issue, I'd open another one if needed during the testing of the new way.
Thank you
