### ISSUE TITLE
Docker container assets are not present in docker image

### ISSUE THREAD

**Issue by gabrieletassoni** [chaskiq/chaskiq#370]
![assets](https://user-images.githubusercontent.com/11076471/115701566-366d6f80-a368-11eb-859f-559c6e6f6140.png)

Using the docker image, at version chaskiq/chaskiq:c2e4510, when I acces using the https://chat.deventa.io, some of the images in the menu are not visible.

**Comment by michelson** [comment]
Hi , which os / system are you using ? recent versions of chaskiq uses emojis as icons, could be that

**Comment by gabrieletassoni** [comment]
Chaskiq is installed using the docker image, so it's a linux.
The os I use for development (the one from which I took that screenshot of the browser) is an Ubuntu 20.10.

**Comment by michelson** [comment]
are you able to see the following:

🏢 <- building
👥 <- people
💬 <- chat bubble
⛺ <- tend
🤖 <- robot
📖 <- book
⚙️ <- cog

**Comment by gabrieletassoni** [comment]
> are you able to see the following:
> 
>  <- building
>  <- people
>  <- chat bubble
>  <- tend
>  <- robot
>  <- book
>  <- cog

Hi, yes, I see them here in github.

![Screenshot from 2021-04-23 16-06-16](https://user-images.githubusercontent.com/11076471/115883291-ee287d00-a44d-11eb-876c-ca9e980e0336.png)

**Comment by michelson** [comment]
it's weird then, I've updated chaskiq last night, some issues were fixed related css rendering , maybe you could update to docker chaskiq:latest ??

**Comment by michelson** [comment]
hello , I've updated icons, not emojis anymore, feel free to reopen or create new issue if you found more problems related with this one
