### ISSUE TITLE
Dev Install on Mac Os, 

### ISSUE THREAD

**Issue by formobi** [chaskiq/chaskiq#375]
Can someone help.
We Installed chaskiq for development on macOS as per the instructions. The server is running but we are getting following error on the browser console
 1>
`Cross-Origin Read Blocking (CORB) blocked cross-origin response http://localhost:3000/packs/js/application-7035ad1151333dba6e4b.js with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.`
2>
Also, on sever getting following error 
`Not delivering sessions due to an invalid api_key`

**Comment by michelson** [comment]
what's your HOST env var ?

**Comment by formobi** [comment]
.env file
HOST=http://localhost:3000
ASSET_HOST=http://localhost:3000
WS=ws://localhost:3000/cable

env on shell:

TERM_SESSION_ID=w0t1p0:D09F072E-1493-46BE-883F-F62649673572
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.lE6bkUVJkj/Listeners
COLORFGBG=0;15
ITERM_PROFILE=Default
XPC_FLAGS=0x0
PWD=/Users/imtiyaz/Desktop/chaskiq
SHELL=/bin/zsh
LC_CTYPE=UTF-8
TERM_PROGRAM_VERSION=3.1.7
TERM_PROGRAM=iTerm.app
***@***.***
***@***.***
/bin:/Users/imtiyaz/.rbenv/shims:/Users/imtiyaz/.rbenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/imtiyaz/mongo443/bin:/Library/Apple/usr/bin
COLORTERM=truecolor
TERM=xterm-256color
HOME=/Users/imtiyaz
TMPDIR=/var/folders/2f/hj6phn514n3b6pv_2m8jkp_m0000gn/T/
USER=imtiyaz
XPC_SERVICE_NAME=0
LOGNAME=imtiyaz
__CF_USER_TEXT_ENCODING=0x0:0:0
ITERM_SESSION_ID=w0t1p0:D09F072E-1493-46BE-883F-F62649673572
SHLVL=1
OLDPWD=/Users/imtiyaz/Desktop/chaskiq/config
ZSH=/Users/imtiyaz/.oh-my-zsh
PAGER=less
LESS=-R
LSCOLORS=Gxfxcxdxbxegedabagacad
RBENV_SHELL=zsh
***@***.***/lib
***@***.***/include
***@***.***/lib/pkgconfig
rvm_prefix=/Users/imtiyaz
rvm_path=/Users/imtiyaz/.rvm
rvm_bin_path=/Users/imtiyaz/.rvm/bin
rvm_version=1.29.12 (latest)
GEM_HOME=/Users/imtiyaz/.rvm/gems/ruby-2.7.2
***@***.***
MY_RUBY_HOME=/Users/imtiyaz/.rvm/rubies/ruby-2.7.2
IRBRC=/Users/imtiyaz/.rvm/rubies/ruby-2.7.2/.irbrc
RUBY_VERSION=ruby-2.7.2
rvm_alias_expanded=
rvm_bin_flag=
rvm_docs_type=
rvm_gemstone_package_file=
rvm_gemstone_url=
rvm_niceness=
rvm_nightly_flag=
rvm_only_path_flag=
rvm_pretty_print_flag=
rvm_proxy=
rvm_quiet_flag=
rvm_ruby_bits=
rvm_ruby_file=
rvm_ruby_make=
rvm_ruby_make_install=
rvm_ruby_mode=
rvm_script_name=
rvm_sdk=
rvm_silent_flag=
rvm_use_flag=
rvm_hook=
_=/usr/bin/env

**Comment by michelson** [comment]
are you visiting the page as http://localhost:3000 or using another dev domain ?

**Comment by formobi** [comment]
Tried both localhost and 127.0.0.1.

**Comment by odovad** [comment]
I had the same issue.

I've changed the HOST and ASSET_HOST to : 

HOST=localhost:3000
ASSET_HOST=localhost:3000
WS=ws://localhost:3000/cable

and it worked, I was able to access to homepage. 


HOST=http://localhost:3000
ASSET_HOST=http://localhost:3000
WS=ws://localhost:3000/cable

didn't
