### ISSUE TITLE
[Bug] Checkbox for usertype does not work (segmeants)

### ISSUE THREAD

**Issue by trulyWHOOOP** [chaskiq/chaskiq#377]
I cannot pick the type of appuser for segments! 

**Reproduction steps**
- Click platform
- Click a segmeant
- Try to deselect one of the user types

The error I get in console: 
```
Uncaught TypeError: e.state.checkedValue.filter is not a function
```

**Comment by trulyWHOOOP** [comment]
@michelson

**Comment by michelson** [comment]
are you using the latest ? could you send my an screencast on the error, I could not replicate it

**Comment by trulyWHOOOP** [comment]
> are you using the latest ? could you send my an screencast on the error, I could not replicate it

using the latest and way 2 busy

**Comment by 7ute** [comment]
@michelson I've juste encountered the same bug.
To reproduce : tick every boxes. When trying to un-tick them, it triggers a "Uncaught TypeError: e.state.checkedValue.filter is not a function"
Seems like checkedValue is expected to be an Array but ends being a String.

![image](https://user-images.githubusercontent.com/8693407/139403780-b99c98b1-b0f1-411f-879e-3e939281d0e8.png)
![image](https://user-images.githubusercontent.com/8693407/139403797-54032e4c-35b0-4146-814c-1bed969b2006.png)
![image](https://user-images.githubusercontent.com/8693407/139404553-d8921fb6-46b5-4fe4-973e-51e1240a2816.png)

**Comment by michelson** [comment]
Hey. Thanks for report this. Whats your system? Os. Browser?

**Comment by 7ute** [comment]
> Hey. Thanks for report this. Whats your system? Os. Browser?

Firefox 93 running on OSX 10.15

**Comment by michelson** [comment]
This problem is due to an update I've made on the service,
please run this command on your server: `rails upgrade_tasks:predicates` that will fix your current segments. 
I will add a patch for the new segments that are added when new app is created
