### ISSUE TITLE
[Huge issue] Message editor for smaller devices does not work

### ISSUE THREAD

**Issue by trulyWHOOOP** [chaskiq/chaskiq#378]
Hey guys, I have a pretty big bug report relating to using the app on smaller devices! 

The message editor does not work on smaller computers, ipads, and sometimes phones. 
When you try to use it you get this issue:
```Uncaught TypeError: Ow is not a function```

To me this is a big issue and should be fixed!

**Comment by michelson** [comment]
we have a fallback editor for mobile, it should display a text area, what do you see , can you share a screenshot ?

**Comment by trulyWHOOOP** [comment]
> we have a fallback editor for mobile, it should display a text area, what do you see , can you share a screenshot ?

I see the fallback editor part but I cannot send messages. When it sends them it is blank

**Comment by michelson** [comment]
good catch @ItsMrReals , I will merge the fix asap

**Comment by trulyWHOOOP** [comment]
Awesome!
