### ISSUE TITLE
error Command "webpack" not found.

### ISSUE THREAD

**Issue by njogia** [chaskiq/chaskiq#402]
I've installed Chaskiq and when I start up, all seems well:

=> Booting Puma
=> Rails 6.1.3.1 application starting in development
=> Run `bin/rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 5.3.1 (ruby 2.7.2-p137) ("Sweetnighter")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 209924
* Listening on http://127.0.0.1:3000
* Listening on http://[::1]:3000
Use Ctrl-C to stop

When I execute "wget http://localhost:3000" this happens:

Started GET "/" for ::1 at 2021-05-31 13:29:06 +0800
   (1.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by HomeController#show as */*
  Rendering layout layouts/application.html.erb
  Rendering home/show.erb within layouts/application
  Rendered home/show.erb within layouts/application (Duration: 0.5ms | Allocations: 216)
[Webpacker] Compiling...
[Webpacker] Compilation failed:
yarn run v1.22.5
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

error Command "webpack" not found.

  Rendered layout layouts/application.html.erb (Duration: 1331.6ms | Allocations: 372816)
Completed 500 Internal Server Error in 1341ms (ActiveRecord: 0.0ms | Allocations: 375671)

Not notifying due to an invalid api_key

ActionView::Template::Error (Webpacker can't find application.js in /root/chaskiq/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
}
):
    35:
    36:
    37:     <%= stylesheet_pack_tag "application" %>
    38:     <%= javascript_pack_tag 'application' %>
    39:     
    40:     
    41:     <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,500,700,800&display=swap" rel="stylesheet">

app/views/layouts/application.html.erb:38
Not delivering sessions due to an invalid api_key

How do I fix this?

**Comment by michelson** [comment]
execute `yarn install `, and then `yarn dev`

**Comment by VinothGox** [comment]
How to use yarn start. package.json start script is not there.

**Comment by michelson** [comment]
is `yarn dev`
