### ISSUE TITLE
babel-cli required for specs

### ISSUE THREAD

**Issue by dp6ai** [chaskiq/chaskiq#428]
**Describe the bug**
I had to install `npm install -g babel-cli` to get the specs running green, maybe worth adding as a dep

**To Reproduce**
Run the specs on a machine without babel-cli

**Comment by michelson** [comment]
which command line are you using to run specs?

**Comment by michelson** [comment]
btw, you need to run `yarn install` before run commands , babel-cli is a dependence in package.json
