### ISSUE TITLE
Slack Integration Not Passing Challenge

### ISSUE THREAD

**Issue by dp6ai** [chaskiq/chaskiq#434]
**Describe the bug**
This [line ](https://github.com/chaskiq/chaskiq/blob/master/app/controllers/api/v1/hooks/provider_controller.rb#L25) No longer works with the slack integration, it needs a response:

```
  def process_event
    response = @integration_pkg.process_event(params)
    render status: 200, json: response
  end
```

This fixes it BUT i assume the change was done for a reason, so i'm not sure how safe it is.

**To Reproduce**
Go through a slack integration and you will receive a message along the lines of challenge_rejected

**Expected behavior**
return the challenge params

**Comment by michelson** [comment]
this is now working as expected, it will handle response properly for Array, String, and Hash responses

thanks for report this
