### ISSUE TITLE
Cannot login to the Chaskiq instance on Heroku

### ISSUE THREAD

**Issue by shyrz** [chaskiq/chaskiq#449]
I deployed an instance on Heroku with the one-click button, but could not login to my account, because the `ADMIN_PASSWORD` variable was generated by the `db:seed` task.
🤔 So whats my password exactly?

**Comment by michelson** [comment]
Hello, you need two env variables for admin
```
ADMIN_EMAIL=
ADMIN_PASSWORD=
```

then run the following task `rails admin_generator`
