### ISSUE TITLE
Gem::LoadError: listen is not part of the bundle

### ISSUE THREAD

**Issue by aw-0** [chaskiq/chaskiq#457]
**Describe the bug**
Whenever you install the latest release from https://github.com/chaskiq/chaskiq.git, and attempt to deploy via Heroku, you will receive the error of `Gem::LoadError: listen is not part of the bundle. Add it to your Gemfile.` when you run `git push heroku master`.

**To Reproduce**
1. Go to https://dev.chaskiq.io/production-configuration/deploy-on-heroku
2. Follow the tutorial until just before **Configure Environment**
3. Run `git push heroku master`

**Expected behavior**
A successful build will be deployed to Heroku.

**Screenshots**
Full logs available @ https://hastebin.com/exadoyibur.yaml

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3

**Comment by aw-0** [comment]
This is also present when deploying via the "Deploy to Heroku" button in the README.

**Comment by michelson** [comment]
I'm sorry for the mistake!
Now it is fixed in master, released docker image too. (tested the deployment in Heroku & docker)
I will close this but feel free to comment/reopen if you find problems with this release.
