### ISSUE TITLE
I18n missing translation 

### ISSUE THREAD

**Issue by krongk** [chaskiq/chaskiq#482]
**Describe the bug**

When I run Chaskiq for the first time, the following error appears:

![image](https://user-images.githubusercontent.com/99572/132116351-6fa97530-6a5a-4ccc-9c6e-dd727c930561.png)

When I try to modify the default configuration, the above error still appears:

![image](https://user-images.githubusercontent.com/99572/132116347-85e2ae88-c8c8-4588-bf6f-91b78fd9a88b.png)

I don’t know if I18n needs any configuration in Chaskiq? Similarly, the "Select Language" option is useless to switch other languages.

![image](https://user-images.githubusercontent.com/99572/132116417-5649de93-101f-4aad-8953-6b0a5621f965.png)

**Comment by michelson** [comment]
Yeah, @krongk, I've just added a PR that fixes this! Look at https://github.com/chaskiq/chaskiq/pull/483; the PR is not merged yet but use it if you want to try it out; I expect to merge this tomorrow.
Also, as a workaround, you can use exec `yarn dev` in another terminal window.

**Comment by michelson** [comment]
thanks for the but report @krongk!

**Comment by krongk** [comment]
Thank you, it's too efficient
