### ISSUE TITLE
Linux Installation Guide is no longer working

### ISSUE THREAD

**Issue by KhaledBinAmir** [chaskiq/chaskiq#484]
Hi,
I have tried multiple time with multiple methods including manual prerequisites installation but I have faced errors. I have tried with EC2 Ubuntu 20.04, the bash script for prerequisites not working using regular user `ubuntu`, tried with `root` but failed at database cloning step.

I am sorry I cannot mention specific errors as there are multiple. My request is to try a test installation.

Thank you.

**Comment by arabie10557** [comment]
same here

**Comment by michelson** [comment]
on EC2 you should try docker, the Linux installation is for development purposes.
for development, purposes try to install rvm. (rvm.io) and then follow the installation steps for rails configuration.

trace of the error is always helpful to figure out what's the error

**Comment by arabie10557** [comment]
> 
> 
> on EC2 you should try docker, the Linux installation is for development purposes. for development, purposes try to install rvm. (rvm.io) and then follow the installation steps for rails configuration.
> 
> trace of the error is always helpful to figure out what's the error

where is the production setup guide for docker?

**Comment by arabie10557** [comment]
I've installed it on docker no errors.....but when i open the url i get white page

**Comment by michelson** [comment]
@arabie10557 check the env vars guide https://dev.chaskiq.io/es/articles/enviroment-variables-configuration

**Comment by arabie10557** [comment]
@michelson  I've used the dev guide not the prod

**Comment by michelson** [comment]
probably you will need to install dependencies, run yarn install, yarn dev, install migrations, etc...
also, add the env vars, that's important

**Comment by arabie10557** [comment]
I did all mentioned here exactly 
https://dev.chaskiq.io/getting-started/docker-for-development

and i tired using yarn dev

**Comment by arabie10557** [comment]
now i'm getting http://127.0.0.1:3000/undefined

**Comment by arabie10557** [comment]
it opens to search box for the help center (wiki) and when i press on go to it redirects to http://127.0.0.1:3000/undefined

**Comment by michelson** [comment]
as I pointed out, you need to set up the env vars; please read the docs carefully before asking questions here.  https://dev.chaskiq.io/es/articles/enviroment-variables-configuration

**Comment by sanjayws** [comment]
its a nightmare to set it up and the documentation is all over the place and broken. Skip the headache, use chatwoot.

**Comment by michelson** [comment]
Hey @sanjayws! sorry to hear that, I guess the Chaskiq installation is a little bit tricky as to work with it needs to run on a local subdomain, so an env variable (a subdomain) is needed in order to work in its completeness. I guess many had fallen in that step. But if u pass that step you will have unlocked the awesomeness 😄 
That procedure is now described here https://dev.chaskiq.io/getting-started (docs updated).

**Comment by sanjayws** [comment]
Thanks for updating the docs, i will give it another try and seek help here from your good self or others. Indeed, chaskiq is awesome, that's why I've been trying to get it running for days without much luck. 

I will try it again thank you @michelson for your arduous work on this project, i deeply appreciate it.

**Comment by sanjayws** [comment]
Finally got it to work and running it behind nginx. Got also to test it with Telegram. It worked fine for a while but it's now now showing new chats, i must clear caches etc and then it shows up.

Question: Do you have a recommended reverse proxy setup for nginx, apache or whatever that i can learn from?

Thank you.
Sanjay

**Comment by michelson** [comment]
hey @sanjayws! happy to hear that it worked, you did it!
regarding the proxy, I think it will depend on your infrastructure if I have to choose I will go with NGINX, but it will depend on the setup. As Chaskiq is a normal rails app any documentation on how to deploy Rails with those servers will be fine.
I suggest deploying this on the digital ocean via DO apps, it's the easy way to deploy this. Also Heroku, but that's more expensive
