### ISSUE TITLE
README link to Chaskiq Install Guide returns error

### ISSUE THREAD

**Issue by lowlyocean** [chaskiq/chaskiq#527]
[This link](https://github.com/chaskiq/chaskiq/blob/65a06acfe045eb5487391270c871a036d180d40f/README.md?plain=1#L105) leads to an error saying:

```Application error: a client-side exception has occurred (developer guidance).```

I was looking for an example of how to integrate Chaskiq into my SaaS once I have it deployed e.g. via Heroku. Are there integration examples to reference?

**Comment by michelson** [comment]
fixed, thanks for report this
