### ISSUE TITLE
duplicated text on app secutity

### ISSUE THREAD

**Issue by silva96** [chaskiq/chaskiq#535]
{I18n.t('identified_users.hint1')}
and 
{I18n.t('identified_users.hmac_hint1')}

Are together and both have the same text.

In production it's shown like this:

![image](https://user-images.githubusercontent.com/4019924/140411856-3381f609-6e24-4c46-9a3b-bec647402088.png)

**Comment by michelson** [comment]
fixed on the latest image/master branch, thanks for the report Benja!
