### ISSUE TITLE
Incomplete Instructions and Many Parts not Working or Missing

### ISSUE THREAD

**Issue by RR-Helpdesk** [chaskiq/chaskiq#570]
**Describe the bug**
I've tried install for over a week, I was able to get the dev environment up on Docker, then part of the way on a normal Ubuntu Service. All of the docs reference Amazon, but for those that don't want AWS I have to manually comb through each doc and figure out how to disable which I finally was able to do and bring the dev server online. Next when moving to production, for some reason the app will not read the .env file. I ended manually exporting the variables in a .bashrc file. Also saving the credentials other than the AWS ones so not work in the credentials.yml.enc.

In both dev or prod I wasn't ever able to get the HOST varilable to take and since there is no docs related to SSL certs, I tried a few options like place some in the /webpack-dev-server/bin/ssl folder then mapping with the "node webpack-dev-server --https --cert ./cert.pem --key ./privkey.pem" commands but that didn't work either. Next not any docs on smtp config but I found some setting in the  production.rb  to switch, however I believe that may be broken as well. I'm using Google Workspace which simply is an smtp domain, port and then on their side a authorized IP, so no user name or password required however I think part of the issue there is it's looking for both of those from what I can see in the errors.

I see something that would indicate options for a separate assets server or storage and found the other options besides AWS, like Google but would be nice to even understand that that reference or if you could self host a sever for that function. 

**To Reproduce**
See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
Ubuntu Server 20.4

**Additional context**

**Comment by RR-Helpdesk** [comment]
#Production Server Up, cannot connect to URL or IP 

bundle exec rails s -b 0.0.0.0 -p 3000

=> Run `bin/rails server --help` for more startup options

W, [2021-12-21T05:35:11.771383 #2594]  WARN -- : Creating scope :enabled. Overwriting existing method BotTask.enabled.
W, [2021-12-21T05:35:11.771692 #2594]  WARN -- : Creating scope :disabled. Overwriting existing method BotTask.disabled.
W, [2021-12-21T05:35:11.773711 #2594]  WARN -- : Creating scope :availables_for. Overwriting existing method BotTask.availables_for.

Puma starting in single mode...
* Puma version: 5.5.1 (ruby 2.7.2-p137) ("Zawgyi")
*  Min threads: 5
*  Max threads: 5
*  Environment: production
*          PID: 2594
* Listening on http://0.0.0.0:3000
Use Ctrl-C to stop
2021-12-21 05:37:02 +0000 HTTP parse error, malformed request: #<Puma::HttpParserError: Invalid HTTP format, parsing fails. Are you trying to open an SSL connection to a non-SSL Puma?>

**Comment by michelson** [comment]
1) Why are you running SSL on dev mode?
2) .env is working, does your env file name is .env and not .env.example ? set the HOST=localhost:3000

**Comment by RR-Helpdesk** [comment]
I'm actually trying to run production. And yes, ENV is named .env and I have /etc/hosts/ configured. For host I have my domain name... https://sub.domain.app .

**Comment by RR-Helpdesk** [comment]
I actually just rebuild the whole thing, I'm not able to get it working either although I think it's not registering the domain name bust get stuck on SSL. In the .env I've also tried dropping the https down to http 

* Listening on http://0.0.0.0:3000
Use Ctrl-C to stop
F, [2021-12-21T13:09:54.905970 #2174] FATAL -- : [29d1d44e-5430-431e-baca-b0e526bd38e8]   
[29d1d44e-5430-431e-baca-b0e526bd38e8] ActionView::Template::Error (The asset "favicon.png" is not present in the asset pipeline.
):
[29d1d44e-5430-431e-baca-b0e526bd38e8]      5:     <%= csrf_meta_tags %>
[29d1d44e-5430-431e-baca-b0e526bd38e8]      6:     <%= csp_meta_tag %>
[29d1d44e-5430-431e-baca-b0e526bd38e8]      7: 
[29d1d44e-5430-431e-baca-b0e526bd38e8]      8:     <link rel="icon" type="image/png" href="<%= asset_url('favicon.png') %>" sizes="16x16">
[29d1d44e-5430-431e-baca-b0e526bd38e8]      9: 
[29d1d44e-5430-431e-baca-b0e526bd38e8]     10:     <meta content='True' name='HandheldFriendly'>
[29d1d44e-5430-431e-baca-b0e526bd38e8]     11:     <meta content='320' name='MobileOptimized'>
[29d1d44e-5430-431e-baca-b0e526bd38e8]   
[29d1d44e-5430-431e-baca-b0e526bd38e8] app/views/layouts/application.html.erb:8

**Comment by RR-Helpdesk** [comment]
Next, I've disabled the force SSL parameter and dropped the https in the domain .env setting but it's still forcing https and getting this....

[https://drive.google.com/file/d/19Xztiptrf3Y0m9LFH-BafrbjJQu8gME0/view?usp=sharing](url)

**Comment by michelson** [comment]
.env file will not work on production that is suited for development.

**Comment by RR-Helpdesk** [comment]
> .env file will not work on production that is suited for development.

Can you elaborate? Your help page, says "Production" and lists out specific .env options for "production" so if this isn't the case, are you planning on updating your docs at all?

`https://dev.chaskiq.io/production-configuration
`

**Comment by michelson** [comment]
We list the variables needed for Chaskiq to work; those env variables are set depending on your system. in the production guides, we don't mention putting this in a .env file unless I'm wrong.

**Comment by michelson** [comment]
Hi, @RevRebel did you solve the issues? I will close this for now but feel free to reopen if you need help.
