### ISSUE TITLE
How to identify the person who left a message?

### ISSUE THREAD

**Issue by B10610204** [chaskiq/chaskiq#571]
![螢幕擷取畫面 2021-12-23 224633](https://user-images.githubusercontent.com/80509622/147256309-246fcfdb-988c-4687-98bb-165755ef0489.png)

**Comment by michelson** [comment]
look in the conversation_parts table the authorable fields.
authorable_id / authorable_part

from rails console / ruby you can call it this way:

c = ConversationPart.last
c.authorable

**Comment by B10610204** [comment]
Will there be a chance to put user information in the data ?
![螢幕擷取畫面 2021-12-23 224633](https://user-images.githubusercontent.com/80509622/147314150-d2acf670-9c32-4569-8fcc-ca7e8a1b0e08.png)

**Comment by michelson** [comment]
No.

**Comment by B10610204** [comment]
Thanks for your reply
