### ISSUE TITLE
unknown attribute for Lead for custom_field in conversation

### ISSUE THREAD

**Issue by Nuxor3000** [chaskiq/chaskiq#587]
In action_trigger.rb in app.services - line 165 :

current_user.update(data["submit"].slice(*opts)) # some condition from settings here?

is not working for a custom_field, it result in a :

[ActiveModel::UnknownAttributeError - unknown attribute 'test for Lead.]

An idea to help me investigate on how to resolve that ?

**Comment by michelson** [comment]
Hi @Nuxor3000, 
have you added the custom attribute from the app settings, right?
do you know from where are you providing the input? this comes from a routing-bot data-retrieval or is it from a routing-bot app?

**Comment by Nuxor3000** [comment]
Yes I added the custom attribute from the app settings.

I created an inboud bot_task and in the editor added a data_retrieval for the custom field.

During the conversation, the error gets fired only for the custom field (not for the regular user fields).

**Comment by michelson** [comment]
I see. the data_retrieval was deprecated. I mean. right now that option is not available from the UI. Does it seem that you are using an old version of Chaskiq. right now for data retrieval, there is the Qualifier plugin that can be added as an App from the routing bot options.

**Comment by Nuxor3000** [comment]
Ok ! Thanks and sorry for that misunderstanding, I reactivated the data_retrieval code I was using before the update as I didn't understand that the qualifier was to be used instead. 

Anyway, I now tried to use the qualifier and I encountered 2 problems :

-1- I still receive an error when I ask for a custom_field created in app/settings :
The error unknown attribute 'test' for Lead is still fired 

and is located in app/graphql/types/app_package_integration_type.rb:53:in `name'
=> object.app_package.name


-2- When I try to ask 2 separated field qualifier, the first is saved, the second one is not saved and the conversation is stopped.

Don't really know where to investigate. An idea ?

**Comment by michelson** [comment]
-1- I still receive an error when I ask for a custom_field created in
app/settings :
can you point the error trace or line where the error was generated?

-2- When I try to ask 2 separated field qualifier, the first is saved, the
second one is not saved and the conversation is stopped.
Can you send me a picture of the form generated by the qualifier? that way,
I could try to replicate it in my env.

**Comment by Nuxor3000** [comment]
/app/services/message_apis/qualifier/presenter.rb:52:in `submit_hook'

/app/models/app_package_integration.rb:210:in `presenter_hook_response'

/app/models/app_package_integration.rb:172:in `call_hook'

/app/graphql/types/app_package_integration_type.rb:62:in `call_hook'

Line is : ctx[:current_user].update(params)
where params is :{"test"=>"typed_value"}

**Comment by michelson** [comment]
Thanks, I will take a look at this asap.

**Comment by Nuxor3000** [comment]
Thanks that's working now !

**Comment by michelson** [comment]
great!
