### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by JamieSlome** [chaskiq/chaskiq#588]
Hey there!

I belong to an open source security research community, and a member (@b1nslashsh) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by michelson** [comment]
Hi Jamie, I will add the SECURITY.md as soon as possible. Meanwhile, can you contact me at miguel@chaskiq.io with the details? I will greatly appreciate it. Thank you.

**Comment by JamieSlome** [comment]
@michelson - thank you for your swift response! 🎉 

Just for reference, you can view the report directly here:

https://huntr.dev/bounties/2b6a7647-8f2b-4510-b40f-c52aedc2820d/

It is private and only accessible to repo maintainers with write permissions.

**Comment by michelson** [comment]
Thanks, @JamieSlome; I've already replied to you in huntr.

**Comment by b1nslashsh** [comment]
@michelson hey sorry for that, 

Just updated the issue please have a look 

Thanks and regards

**Comment by JamieSlome** [comment]
@michelson - great ❤️

**Comment by michelson** [comment]
Thanks, bug fixed, I've reported it already on huntr
