### ISSUE TITLE
Error in admin login in production (both heroku and digital ocean platform)

### ISSUE THREAD

**Issue by roadtouk** [chaskiq/chaskiq#598]
**Describe the bug**
I followed the [production guides here ](https://dev.chaskiq.io/production-configuration) firstly with DO app platform and got it to to the point the app deployed successfully but couldn't login with admin email and password. Upon clikcing sign in, it shows an error and in console `POST https://<host>/oauth/token.json [HTTP/1.1 400 Bad request]`

Then I tried deploying in heroku with the **Deploy in Heroku" button. Ended up with the same result.

Response header to the POST request for login is as below:

```
HTTP/1.1 400 Bad Request
Server: Cowboy
Date: Wed, 19 Jan 2022 13:42:39 GMT
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, PUT, OPTIONS
Access-Control-Expose-Headers: 
Access-Control-Max-Age: 7200
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: strict-origin-when-cross-origin
Cache-Control: no-store
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Www-Authenticate: Bearer realm="Doorkeeper", error="invalid_grant", error_description="The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."
Set-Cookie: _chaskiq_session=<cookie-ID>; path=/; secure; HttpOnly
X-Request-Id: 24689b64-78ad-426e-81e9-cffb13418173
X-Runtime: 0.005833
Strict-Transport-Security: max-age=63072000; includeSubDomains
Vary: Origin
Transfer-Encoding: chunked
Via: 1.1 vegur
```

**To Reproduce**
1. Deploy a production env with DO-app or even heroku.
2. Attempt first login with admin email and password from env vars

**Expected behavior**
Login to dashboard?

**Desktop (please complete the following information):**
 - OS: [win 10, win 11]
 - Browser [chrome-v97.04692.71, mozilla-v96.0.1]

**Comment by michelson** [comment]
Hello. Did you run the db migrations, seeds and admin gen tasks?

**Comment by roadtouk** [comment]
Yes. I have done that but still no luck.

**Comment by michelson** [comment]
This might be related with an upgrade on the doorkeeper gem:
solution ref here:
https://github.com/chaskiq/chaskiq/issues/711
