### ISSUE TITLE
Team members duplicated in Chaskiq app

### ISSUE THREAD

**Issue by Pnlpz** [chaskiq/chaskiq#638]
There were new members added to our account in Chaskiq, but their profiles appeared duplicated in the app, which was uncommon. We proceeded to delete the duplicates, and it all kept functioning in a normal way. 
Just leaving this issue in case there are more reports from other users experiencing the same. 

![image](https://user-images.githubusercontent.com/32583305/153448431-121eecf5-2bdf-4235-83a7-c394184e15a0.png)

**Comment by michelson** [comment]
Hi there. Those emails are not identical. One is .com the other is .cm

**Comment by michelson** [comment]
I will close this, please let me know if there is anything in this regard that can be discussed
