### ISSUE TITLE
Profile picture cannot be updated and it does not show in chat (in users' view)

### ISSUE THREAD

**Issue by Pnlpz** [chaskiq/chaskiq#641]
I changed my profile picture a couple of weeks ago, but now, after doing some tests in the chat, I noticed my picture was not showing. 

![image](https://user-images.githubusercontent.com/32583305/154569130-c5aac812-d0b6-43ca-a979-44d8ecdc1cdc.png)

Now, when I try to update the picture in my profile, I am not able to do so, as the option is not there. 
![image](https://user-images.githubusercontent.com/32583305/154569504-2f6ee248-2c40-4a34-a839-3738c5195b60.png)

We had another user whose picture was not hers (it was your profile picture), and actually, people called her 'Miguel', too 😂. 

When I reply from Slack, the user (customer) sees no profile picture, and a weird username:
![image](https://user-images.githubusercontent.com/32583305/154569937-7e03a831-4d6b-4f42-b1c1-20468b60dd4b.png)

Let me know if you need to do some tests to check or replicate this issue.

**Comment by michelson** [comment]
Hello @Pnlpz!
I think those are two issues, 
the first issue is probably the fallback of the author to the channel on method `get_agent_from_event(event)` on the `slack/api.rb`; in which it checks if the message event from slack comes with an email address identifiable with one of the Chaskiq agents, if there are no matches, then it will fall back to the first agent on the app, and that's me! 😂. So double-check the agent's email matches with the slack user.
The second issue is probably that you used the @ string to point one team member on Slack; when slack delivers the event to Chaskiq, it delivers with that rare <xxxx> identification. Right now Chaskiq has no capabilities to parse that in a more human-readable thing

**Comment by michelson** [comment]
and there is a bug on the avatar upload, I looking into that

**Comment by michelson** [comment]
@Pnlpz the image issue was solved, it was an issue on my S3 bucket, very strange but it is solved, I can see your avatar now :)

**Comment by michelson** [comment]
also I can see that the email issue that I mentioned is due to the error on an email. check the one with the `.cm`

**Comment by Pnlpz** [comment]
Thanks @michelson!!! I'm looking into it now. I'll let you know if the issue persists  😉

**Comment by Pnlpz** [comment]
I deleted the users who had spelling mistakes in their emails and sent them the invitations to join the team again. Now, there is only 1 invitation that I can see in the 'Invitations', even though I sent 3. 
Anyway, I'll be checking this during the day. 🧐

**Comment by michelson** [comment]
the other two invitations might be ended in the team tab, please check if those agents are already added

**Comment by Pnlpz** [comment]
Yeap, I sent 3 invitations and all of them appear in the Team tab, but only one of them appears in the invitations tab. I'll request them to check if they received the invitation or not.
