### ISSUE TITLE
docker-compose up webpacker throws an error

### ISSUE THREAD

**Issue by psschand16** [chaskiq/chaskiq#644]
**Describe the bug**
unable to  get webpacker up and running

I was following the tutorial here
https://dev.chaskiq.io/en/articles/docker-for-development

**To Reproduce**

>>>docker-compose up webpacker
Recreating chaskiq_webpacker_1 ... done
Attaching to chaskiq_webpacker_1
webpacker_1  | yarn run v1.13.0
webpacker_1  | error Command "webpack-dev-server" not found.
webpacker_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
chaskiq_webpacker_1 exited with code 1

>>>docker-compose run webpacker yarn install
Creating chaskiq_webpacker_run ... done
yarn install v1.13.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
error sass@1.49.7: The engine "node" is incompatible with this module. Expected version ">=12.0.0". Got "10.24.0"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: 1

**Desktop (please complete the following information):**
 - OS: windows, ubuntu wsl

**Additional context**
webpacker_1  | yarn run v1.13.0
webpacker_1  | error Command "webpack-dev-server" not found.
webpacker_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by michelson** [comment]
Hi There, last night we release a new release that does not use webpacker, I've updated the instructions for the docker development guide. if the current docker-compose does not work for you, please try this one

https://gist.github.com/michelson/b461ab46604dcaa02f5bd65533973119

do a clean build and follow the updated instructions on the article. please let me know how it goes so we can help you to make this work. https://dev.chaskiq.io/getting-started/docker-for-development

best!

**Comment by psschand16** [comment]
@michelson Thanks for helping me out.

I tried pulling the latest release and doing a clean build.

<img width="301" alt="A Screenshot 2022-02-19 111221" src="https://user-images.githubusercontent.com/61744673/154799707-48049470-6a37-4e54-bdbf-5f12b8229942.png">

everything worked except rails

D:\td\pro2\A\chaskiq>docker-compose run rails rake db:seed
[+] Running 2/0
 - Container chaskiq-postgres-1  Running                                                      0.0s
 - Container chaskiq-redis-1     Running                                                      0.0s

D:\td\pro2\A\chaskiq>docker-compose run rails rake admin_generator
[+] Running 2/0
 - Container chaskiq-redis-1     Running                                                      0.0s
 - Container chaskiq-postgres-1  Running                                                      0.0s

D:\td\pro2\A\chaskiq>docker-compose up rails
[+] Running 3/3
 - Container chaskiq-postgres-1  Running                                                      0.0s
 - Container chaskiq-redis-1     Running                                                      0.0s
 - Container chaskiq-rails-1     Created                                                      0.1s
Attaching to chaskiq-rails-1
chaskiq-rails-1  | Installing foreman...
chaskiq-rails-1  | Fetching foreman-0.87.2.gem
chaskiq-rails-1  | Successfully installed foreman-0.87.2
chaskiq-rails-1  | 1 gem installed
chaskiq-rails-1  | 10:49:17 web.1  | started with pid 18
chaskiq-rails-1  | 10:49:17 js.1   | started with pid 19
chaskiq-rails-1  | 10:49:17 css.1  | started with pid 20
chaskiq-rails-1  | 10:49:18 js.1   | /app/esbuild.config.mjs:1
chaskiq-rails-1  | 10:49:18 js.1   | import esbuild from 'esbuild';
chaskiq-rails-1  | 10:49:18 js.1   |        ^^^^^^^
chaskiq-rails-1  | 10:49:18 js.1   | 
chaskiq-rails-1  | 10:49:18 js.1   | SyntaxError: Unexpected identifier
chaskiq-rails-1  | 10:49:18 js.1   |     at Module._compile (internal/modules/cjs/loader.js:723:23)
chaskiq-rails-1  | 10:49:18 js.1   |     at Object.Module._extensions..js (internal/modules/cjs/loa
der.js:789:10)
chaskiq-rails-1  | 10:49:18 js.1   |     at Module.load (internal/modules/cjs/loader.js:653:32)
chaskiq-rails-1  | 10:49:18 js.1   |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
chaskiq-rails-1  | 10:49:18 js.1   |     at Function.Module._load (internal/modules/cjs/loader.js:5
85:3)
chaskiq-rails-1  | 10:49:18 js.1   |     at Function.Module.runMain (internal/modules/cjs/loader.js
:831:12)
chaskiq-rails-1  | 10:49:18 js.1   |     at startup (internal/bootstrap/node.js:283:19)
chaskiq-rails-1  | 10:49:18 js.1   |     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
chaskiq-rails-1  | 10:49:19 js.1   | exited with code 1
chaskiq-rails-1  | 10:49:19 system | sending SIGTERM to all processes
chaskiq-rails-1  | 10:49:19 css.1  | rails aborted!
chaskiq-rails-1  | 10:49:19 css.1  | SignalException: SIGTERM


I also tried the docker compose file you shared on the below link, but it failed on yarn installation
https://gist.github.com/michelson/b461ab46604dcaa02f5bd65533973119

<img width="475" alt="image" src="https://user-images.githubusercontent.com/61744673/154799885-f8634648-a23e-4fd4-8d62-079f4067669d.png">

D:\td\pro2\B\chaskiq>docker-compose run rails yarn install
[+] Running 2/0
 - Container chaskiq-redis-1     Running                                     0.0s
 - Container chaskiq-postgres-1  Running                                     0.0s
yarn install v1.13.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Ex
cluding it from installation.
info esbuild-android-arm64@0.14.12: The platform "linux" is incompatible with this
 module.
info "esbuild-android-arm64@0.14.12" is an optional dependency and failed compatib
ility check. Excluding it from installation.
info esbuild-android-arm64@0.14.12: The CPU architecture "x64" is incompatible wit
h this module.
info esbuild-darwin-64@0.14.12: The platform "linux" is incompatible with this mod
ule.
info "esbuild-darwin-64@0.14.12" is an optional dependency and failed compatibilit
y check. Excluding it from installation.
info esbuild-darwin-arm64@0.14.12: The platform "linux" is incompatible with this
module.
info "esbuild-darwin-arm64@0.14.12" is an optional dependency and failed compatibi
lity check. Excluding it from installation.
info esbuild-darwin-arm64@0.14.12: The CPU architecture "x64" is incompatible with
 this module.
info esbuild-freebsd-64@0.14.12: The platform "linux" is incompatible with this mo
dule.
info "esbuild-freebsd-64@0.14.12" is an optional dependency and failed compatibili
ty check. Excluding it from installation.
info esbuild-freebsd-arm64@0.14.12: The platform "linux" is incompatible with this
 module.
info "esbuild-freebsd-arm64@0.14.12" is an optional dependency and failed compatib
ility check. Excluding it from installation.
info esbuild-freebsd-arm64@0.14.12: The CPU architecture "x64" is incompatible wit
h this module.
info esbuild-linux-32@0.14.12: The CPU architecture "x64" is incompatible with thi
s module.
info "esbuild-linux-32@0.14.12" is an optional dependency and failed compatibility
 check. Excluding it from installation.
info esbuild-linux-arm@0.14.12: The CPU architecture "x64" is incompatible with th
is module.
error is-plain-obj@4.0.0: The engine "node" is incompatible with this module. Expe
cted version ">=12". Got "10.24.0"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this co
mmand.


I hope to get this fixed.
Thanks.

**Comment by michelson** [comment]
run the `yarn install `command on the rails image

**Comment by michelson** [comment]
Also, I've tested in my local env, and I made a new Pull Request with an updated docker-compose, https://github.com/chaskiq/chaskiq/pull/645; if you want, you can test it out and let us know if it works for you.

**Comment by psschand16** [comment]
Thank you @michelson , 
I pulled the latest code and did fresh build.

It did work on the first run .
I was able to login to web application.

on subsequent run, rails service failed .
pasting the error trail snippet below.

>>>chaskiq-rails-1  | 09:11:04 css.1  | Rebuilding...
chaskiq-rails-1  | 09:11:09 css.1  | Done in 4859ms.
chaskiq-rails-1  | 09:11:10 web.1  | A server is already running. Check /app/tmp/p
ids/server.pid.
chaskiq-rails-1  | 09:11:10 web.1  | Exiting
chaskiq-rails-1  | 09:11:10 web.1  | Not notifying due to an invalid api_key
chaskiq-rails-1  | 09:11:11 web.1  | exited with code 1
chaskiq-rails-1  | 09:11:11 system | sending SIGTERM to all processes
chaskiq-rails-1  | 09:11:11 css.1  | rails aborted!
chaskiq-rails-1  | 09:11:11 css.1  | SignalException: SIGTERM
chaskiq-rails-1  | 09:11:11 css.1  | 
chaskiq-rails-1  | 09:11:11 css.1  | Tasks: TOP => tailwindcss:watch
chaskiq-rails-1  | 09:11:11 css.1  | (See full trace by running task with --trace)
chaskiq-rails-1  | 09:11:11 js.1   | terminated by SIGTERM
chaskiq-rails-1  | 09:11:12 css.1  | exited with code 1
chaskiq-rails-1 exited with code 1

**Comment by michelson** [comment]
hello, it seems that the server PID does not get removed when the server restart; I would suggest replacing the command on the docker-compose from this:

    command: ./bin/dev

to this

    command: bash -c "rm -f tmp/pids/server.pid && ./bin/dev"

**Comment by psschand16** [comment]
@michelson Thanks alot for guiding me and helping me to fix this.

its working now and seems stable.

**Comment by michelson** [comment]
Great! glad to hear that is working 👍
