### ISSUE TITLE
Error on access quick replies with new agents

### ISSUE THREAD

**Issue by marcio-haup** [chaskiq/chaskiq#646]
**Describe the bug**
After dokcer image 0d7af8f all users i create can't access quick replies

**To Reproduce**
1. install chaskiq docker version 0d7af8f  
2. Create new quick replies with manager
3. Create a new agent
4. Try use quick replies in a conversations

**Expected behavior**
Like in before versions, i expect that a list of quick replies open

**Screenshots**
![image](https://user-images.githubusercontent.com/4932378/155016145-d1fe867b-fb01-489c-9eb1-d096ab1e761b.png)

**Desktop:**
 - OS: Windows 10
 - Browser Chrome(98.0.4758.102), Firefox(97.0.1) and Edge(98.0.1108.56)

**Additional context**
The Chaskiq was instaled at Digital Ocean fallowing the production tutorial (https://dev.chaskiq.io/production-configuration/production-deployment-on-digital-ocean-apps)

**Comment by michelson** [comment]
Hello Marcio, that's a permission error, so that user has a role that has no access to that feature. You will need to set another position in the settings -> team section.

**Comment by marcio-haup** [comment]
Hello, thanks for the anwser.

I have tried all types of access list(manager, agent and admin), none of this can access quick replies.

I reinstaled all application several times, and i can't make quick replies work properly. Only with the tag ef6a82e and behind

**Comment by michelson** [comment]
admin role should have all manage access, try the latest tag version and add the role again, something changed on the role system from the oldest version to the newest ones. indeed the last migration file from /db/migrations is the migration that handles that update.

**Comment by marcio-haup** [comment]
I couldn't get this to work.
Even with a new installation and the latest tag version.

Same error, and it is the only error for me

**Comment by michelson** [comment]
what is the role that the agent has? you can see that in the database
agents -> "role" field.

**Comment by marcio-haup** [comment]
The field role doesn't exists in agents table.
I found 'roles' table, and my agent is manager(at this moment), I've already tried all the others values

**Comment by michelson** [comment]
ah yes, sorry. it's the role table with the role field. which values did
you try? with the `admin` role it should be working

**Comment by marcio-haup** [comment]
Yes, with admin works fine, but I don't want the agents with admin power

**Comment by michelson** [comment]
Afk, check the permissions.yml in which you could customize the roles. Just
restart the server once update that file.

**Comment by michelson** [comment]
reopen if you need more help in this topic,
thanks
