### ISSUE TITLE
Website chat widget snippet does not work

### ISSUE THREAD

**Issue by psschand16** [chaskiq/chaskiq#653]
**Describe the bug**
I just deployed chaskiq to heroku.
I have pasted the below code snippet to my website, I do not see any chat window loading to initiate chat.

      <script>
        (function(d,t) {
          var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
          g.src="https://chatmink.herokuapp.com/embed.js"
          s.parentNode.insertBefore(g,s);
          g.onload=function(){
            new window.ChaskiqMessengerEncrypted({
              domain: 'https://chatmink.herokuapp.com',
              ws:  'wss://chatmink.herokuapp.com/cable',
              app_id: "86z64CMNcagDpfS6qdkSWT1Q",
              data: "YOUR_ENCRYPTED_JWE_DATA",
              lang: "USER_LANG_OR_DEFAULTS_TO_BROWSER_LANG" 
            })
          }
        })(document,"script");
      </script>

**Expected behavior**
I should see a chat window pop up on the website

**Additional context**
I see the following errors on console
<img width="422" alt="image" src="https://user-images.githubusercontent.com/61744673/155394459-ff6aeffe-d3dc-4918-8e9a-30d19c8704fc.png">

also I donot see any chat window pop up in chat tester, is that ok?

**Comment by michelson** [comment]
422 is the error of unauthorized origin. So you have to do 2 things:
1) set the activate messenger on settings -> messenger settings
2) in the app settings add the domain url of the host app (the domain in
which the chat will be displayed) or put and asterisk * if you want to
accept any origin (inherently insecure)

**Comment by psschand16** [comment]
Thanks :) 
That did Work
