### ISSUE TITLE
Team invitation returns a server error

### ISSUE THREAD

**Issue by psschand16** [chaskiq/chaskiq#654]
**Describe the bug**

**To Reproduce**
Inviting someone by email  to a team returns a server error

**Expected behavior**
An invitation email is sent to team member.

**Screenshots**
![image](https://user-images.githubusercontent.com/61744673/155514763-387206e9-decd-414e-9224-689244b1456b.png)

**Additional context**
<img width="940" alt="image" src="https://user-images.githubusercontent.com/61744673/155515308-7c14c5d5-60f0-4dbd-8c39-ed30e1a50f81.png">

**Comment by michelson** [comment]
you need to check the logs on the server-side, probably you did not set your amazon ses credentials for email dispatching

**Comment by psschand16** [comment]
@michelson yes, you are right.

I found the follwing error on application logs.

2022-02-28T12:05:39.499300+00:00 app[web.1]: E, [2022-02-28T12:05:39.499210 #6] ERROR -- : [d9e1c906-d775-445c-bef0-699b1688de49] Email address is not verified. The following identities failed the check in region EU-WEST-1: someone@gmail.com.
I found out my SES is in sandbox mode.
When your SES account is in "sandbox" mode, you can:

Only send from verified domains and email addressed, and
Only send to verified domains and email addresses
In order to send to anyone else, you must move your account out of sandbox mode by contacting AWS support and requesting it:
https://docs.aws.amazon.com/console/ses/sandbox

So I had to manually verify email addresses in SES to resolve this.

do we have an alternative to SES here?

**Comment by michelson** [comment]
yes, you will need to set up your SES account or add any SMTP credentials with:

```
SMTP_DELIVERY_METHOD=smtp
SMTP_ADDRESS=
SMTP_USERNAME=
SMTP_PASSWORD=
```

note that if you use the normal smtp you may loose the email reception, that's the capability of chaskiq to receive emails
