### ISSUE TITLE
Team roles not clearly defined

### ISSUE THREAD

**Issue by psschand16** [chaskiq/chaskiq#661]
**Describe the bug**
I tried to login with a user that has an AGENT Role.
I see the agent has access to "create new app" 

**Expected behavior**
An agent should not have access to creating apps only admin should

**Additional context**
I consider this as a security flaw.

**Comment by michelson** [comment]
the role is based per app. but the app creation is outside the domain of an "app", so basically, there is no role outside an app. 
if you want to disable app creation you can use `DISABLE_APP_CREATION = true` on your env vars.
- This is not security flaw.
