### ISSUE TITLE
where is the rest api?

### ISSUE THREAD

**Issue by NitinNR** [chaskiq/chaskiq#668]
is there rest api available for chaskiq?

**Comment by michelson** [comment]
Hi, the API is graphql, you can access the api explorer visiting /graphiql on your local installation, also you can explore it on [app.chaskiq.io/api-explorer](https://chaskiq.io/api-explorer)

**Comment by NitinNR** [comment]
would you please explain what's going on here : https://chaskiq.io/api-explorer.becoz it's quite confusing to get understand.

**Comment by michelson** [comment]
GraphQL is a standard, when you learn that, then it will be less confusing.

**Comment by NitinNR** [comment]
ok ! thanks
