### ISSUE TITLE
Integrate WhatsApp web via Online Live Support

### ISSUE THREAD

**Issue by harismateen** [chaskiq/chaskiq#698]
**Is your feature request related to a problem? Please describe.**
Hi, Would like to integrate chaskiq with whatsapp via Online Live Support

**Describe the solution you'd like**
Able to connect with users via whatsapp web (send and received whatsapp messages)

**Additional context**
API Docs: https://online-live-support.com/whatsapp-api-documentation/
User Guide: https://docs.online-live-support.com/

**Comment by michelson** [comment]
the solution does not seem to be an official WhatsApp channel, so it's unlikely for us to integrate the channel, sorry.

**Comment by michelson** [comment]
Not sure whats the question but we do not integrate of unofficial whatsapp
channels, only official providers. Sorry
