### ISSUE TITLE
S3 endpoint not exposed

### ISSUE THREAD

**Issue by jalberto** [chaskiq/chaskiq#700]
I would like to use a S3 compatible service, but chaskiq do not expose the endpoint configuration.

Is this intentional? 

https://github.com/chaskiq/chaskiq/blob/6fc28826ef9af1ba79acd82e6210cf2892881450/config/storage.yml#L16

**Comment by michelson** [comment]
right, we could activate that property. could you submit a PR with the endpoint that defaults to AWS?

**Comment by vpedrosa** [comment]
This feature is a must for reducing self-hosting cost. Usage of Cloudflare R2 or Minio would be great.

**Comment by michelson** [comment]
https://github.com/chaskiq/chaskiq/discussions/464

https://github.com/chaskiq/chaskiq/pull/939
