### ISSUE TITLE
Page not working

### ISSUE THREAD

**Issue by eklipse18** [chaskiq/chaskiq#710]
**Describe the bug**
Nothing is happening after running the server, a blank page is shown:
![image](https://user-images.githubusercontent.com/61617820/162620805-62ee068f-1e80-4759-821c-9880bcb173a8.png)

**To Reproduce**
I've followed the exact docker installation instructions as shown on https://dev.chaskiq.io/getting-started/docker-for-development

**Expected behavior**
A starting page should have been shown

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Brave
 - Version: latest

**Comment by michelson** [comment]
you need to add environment variables to your .env file
```
HOST=http://localhost:3000
WS=ws://localhost:3000/cable
```

**Comment by eklipse18** [comment]
Now it gives me `A server is already running. Check /app/tmp/pids/server.pid` for some reason, although no other docker container is running

**Comment by michelson** [comment]
remove the `/app/tmp/pids/server.pid` file and try again. somehow the pid was not removed when you restarted the server. is not common but sometimes happen

**Comment by eklipse18** [comment]
Ah so thats what it means, thanks!

**Comment by eklipse18** [comment]
Also, what should be running on localhost:3001?
Because the console is filled with such error messages:
![image](https://user-images.githubusercontent.com/61617820/162744117-0855ed9b-ffce-4899-933c-4a2e5526ae50.png)
And also there's just this error alert:
![image](https://user-images.githubusercontent.com/61617820/162744181-7379e195-f7ca-4659-ac9a-5b30e1f05d2c.png)

**Comment by michelson** [comment]
the 3001 port is a NodeJS server that listens to JS changes and sends messages to the UI in order to reload it.

**Comment by michelson** [comment]
it seems that we need to open that port in the development docker container

**Comment by michelson** [comment]
in the docker-compose.yml file add the ports on the rails app, something like:


```yml
  rails:
    <<: *backend
    command: ./bin/dev
    ports:
      - '3000:3000'
      - '3001:3001'
```

**Comment by michelson** [comment]
if that works don't hesitate to send us a pull request :)

**Comment by eklipse18** [comment]
Hey I'm sorry to trouble you again, but now when I try to login it says that my grant is invalid?
![image](https://user-images.githubusercontent.com/61617820/162756256-21a5cec0-55f4-4150-9317-eb67761eea9f.png)

**Comment by eklipse18** [comment]
What can I do to fix it?

**Comment by michelson** [comment]
Hi, try to update the doorkeeper application by doing the following:

enter the rails console: open a terminal and run: rails c

then write the following:

Doorkeeper::Application.last.update(confidential: false)

**Comment by eklipse18** [comment]
Nope still the same unfortunately

**Comment by michelson** [comment]
Hi, maybe you could do

Doorkeeper::Application.first.update(confidential: false)

**Comment by eklipse18** [comment]
Nope, sadly. Have you ever encountered this error before?

**Comment by michelson** [comment]
Hi, yes I've seen this error when the database is not populated or the
admin is not created.
did you run the seed task and the admin generation task? you could check
that by entering the rails console and see if there are any agents created

> rails c
then
Agent.all

best

**Comment by eklipse18** [comment]
Yep there's a `bot@1-chaskiq` account and a `bot@2-chaskiq` account. Should there also be my admin account? btw I've already specified the credentials in `.env`

**Comment by michelson** [comment]
there should be an admin user.
Did you run the admin_generator task?

**Comment by eklipse18** [comment]
yep, `docker-compose run rails rake admin_generator` right?
![image](https://user-images.githubusercontent.com/61617820/163466037-2f68720f-0ca5-4230-819d-c17f2dfed5c4.png)

**Comment by michelson** [comment]
maybe the ADMIN_PASSWORD is invalid? try to make one password 6 characters length or more

**Comment by eklipse18** [comment]
It was shorter than 6 characters, I made it longer and then reran the `admin_generator` task, and I think I've fixed the issue, thanks!

**Comment by michelson** [comment]
Glad to hear that @Vthechamp22 !
