### ISSUE TITLE
Authentication issues after resetting password

### ISSUE THREAD

**Issue by jalberto** [chaskiq/chaskiq#711]
**Describe the bug**
After upgrade to the latest version and performed a password reset, I cannot log in

**To Reproduce**
1. Upgrade to latest docker image
2. request a password reset
3. rest your password
4. try to login

![image](https://user-images.githubusercontent.com/99927/162738930-9d2e308b-e9b2-4794-8edc-88ddf0dfe59c.png)

In other hand, the email/password seems to be sent multiple times as parameters, is that expected?

Even after resetting the password from the console, I get a 401 (`agent.password=foo ; agent.save`)

**Comment by michelson** [comment]
Hi, try to update the doorkeeper application doing the following:

enter the rails console: open a terminal and run: `rails c`

then write the following:

`Doorkeeper::Application.last.update(confidential: false)`

let me know if it worked ok.

**Comment by jalberto** [comment]
Yep, that did the trick, thanks!

**Comment by michelson** [comment]
glad to hear
