### ISSUE TITLE
Guided tours configuration JS errors.

### ISSUE THREAD

**Issue by hploscar** [chaskiq/chaskiq#722]
**Describe the bug**
Guided tours Steps can not be configured with included HTML.

**To Reproduce**
1. Go to "guided tours"
2. Click on "Create New Campaign"
3. Click on "Settings"  
4. Setup url (you can set your chat tester to test, but it happens with any url tested), scheduled time and hidden constraints.
5. Click on "Editor"
6. Click on "+" to open target to configure.
7. Click on "+" card at the bottom select a tag.
8. Select a tag.
9.  Click on step textbox and use the "+" at the left to insert HTML. 
10. Select any element but image.

**Expected behavior**
The HTML should be included in guided tour step.

**Screenshots**
![Captura de pantalla de 2022-04-18 12-35-52](https://user-images.githubusercontent.com/8766769/163857437-e2b1edd1-3a68-4cff-968d-4e223666478d.png)

**Desktop (please complete the following information):**
 - OS: Fedora 35
 - Browser Brave
 - Version 1.36.109 Chromium: 99.0.4844.51 (Build oficial) (64 bits)

**Additional context**
When configuring steps for a guided tour, the target window js console throws errors when resizing.

**Comment by hploscar** [comment]
![Captura de pantalla de 2022-04-18 09-29-40](https://user-images.githubusercontent.com/8766769/163859026-2294aeda-3455-4d90-9077-f036416e772d.png)

**Comment by michelson** [comment]
I believe the #733 fixes this. sorry for the delay on this.
