### ISSUE TITLE
Console does not work properly after restarting chaskiq

### ISSUE THREAD

**Issue by f10atin9** [chaskiq/chaskiq#790]
**Describe the bug**
I have successfully run the chaskiq system in k8s and configured the services on my website.
I restarted the deployment of chaskiq in k8s and tried to update to the latest chaskiq docker image, when the web backend became unavailable
![console not work](https://user-images.githubusercontent.com/36705019/183832877-e8a7ac3e-b62c-4848-9405-287a7465c54c.png)

But it looks normal on the chaskiq chat icon on my website
I think my postgres and redis are fine and I don't have to run
```
bundle exec rails db:setup
bundle exec rails db:migrate
bundle exec rails db:seed
bundle exec rails admin_generator
```

**To Reproduce**
Deploy chaskiq-related services in a k8s cluster, then update the image

**Expected behavior**
I expect to be able to re-access my administration page

**Desktop (please complete the following information):**
k8s1.21

**Additional context**
log in chaskiq container：
```
 I, [2022-08-10T06:35:44.660173 #1]  INFO -- : [bdd520509f1f2b7492a08e952b878053] Started GET "/" for 192.168.0.2 at 2022-08-10 06:35:44 +0000
 I, [2022-08-10T06:35:44.662739 #1]  INFO -- : [bdd520509f1f2b7492a08e952b878053] Processing by ArticlesController#show as HTML
 I, [2022-08-10T06:35:44.667158 #1]  INFO -- : [bdd520509f1f2b7492a08e952b878053] Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.6ms | Allocations: 740)
 F, [2022-08-10T06:35:44.667969 #1] FATAL -- : [bdd520509f1f2b7492a08e952b878053]   
 [bdd520509f1f2b7492a08e952b878053] NoMethodError (undefined method `app' for nil:NilClass):
 [bdd520509f1f2b7492a08e952b878053]   
 [bdd520509f1f2b7492a08e952b878053] app/controllers/articles_controller.rb:15:in `messenger_data'
 [bdd520509f1f2b7492a08e952b878053] app/controllers/articles_controller.rb:7:in `show'
```

**Comment by f10atin9** [comment]
I changed the HOST and WS of the environment variable as issue #306  and it doesn't seem to help

**Comment by f10atin9** [comment]
It looks like it's caused by ` NoMethodError (undefined method `app' for nil:NilClass):` , but I don't know why it triggers this

**Comment by michelson** [comment]
Hi, the error means that the HOST is not the same as the domain you are visiting from, (can you confirm that?) 
so it tries to render the help center and fails to render it because the help center domain "app" is also not found.
The error of this logic raises on `app/controllers/articles_controller.rb:15`
did you restart the application after changed the HOST/WS?

**Comment by f10atin9** [comment]
> Hi, the error means that the HOST is not the same as the domain you are visiting from, (can you confirm that?) so it tries to render the help center and fails to render it because the help center domain "app" is also not found. The error of this logic raises on `app/controllers/articles_controller.rb:15` did you restart the application after changed the HOST/WS?

I checked again that HOST and WS are correct

**Comment by michelson** [comment]
did you restart the application after changed the HOST/WS?

**Comment by michelson** [comment]
you could also put a "puts request.subdomain.first" in order to debug what's the value of the detected subdomain, in the line app/controllers/articles_controller.rb:15

**Comment by f10atin9** [comment]
> did you restart the application after changed the HOST/WS?

I just added other variables about local storage and then it went wrong.

**Comment by michelson** [comment]
which ones? what errors did you get?

**Comment by f10atin9** [comment]
> which ones? what errors did you get?

It's not that's fault, I mean, I didn't modify HOST and WS, just added other environment variables and the problem was already there

**Comment by michelson** [comment]
Sorry, I don't get what you mean. Can you be more descriptive about the errors you get?

**Comment by f10atin9** [comment]
I did not modify the HOST and WS and then restart the container of chaskiq, the page becomes like this

![image](https://user-images.githubusercontent.com/36705019/183921110-a1780eee-dcf0-4285-bf27-bb14019a6ef7.png)


log in chaskiq container：
```
 I, [2022-08-10T06:35:44.660173 #1]  INFO -- : [bdd520509f1f2b7492a08e952b878053] Started GET "/" for 192.168.0.2 at 2022-08-10 06:35:44 +0000
 I, [2022-08-10T06:35:44.662739 #1]  INFO -- : [bdd520509f1f2b7492a08e952b878053] Processing by ArticlesController#show as HTML
 I, [2022-08-10T06:35:44.667158 #1]  INFO -- : [bdd520509f1f2b7492a08e952b878053] Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.6ms | Allocations: 740)
 F, [2022-08-10T06:35:44.667969 #1] FATAL -- : [bdd520509f1f2b7492a08e952b878053]   
 [bdd520509f1f2b7492a08e952b878053] NoMethodError (undefined method `app' for nil:NilClass):
 [bdd520509f1f2b7492a08e952b878053]   
 [bdd520509f1f2b7492a08e952b878053] app/controllers/articles_controller.rb:15:in `messenger_data'
 [bdd520509f1f2b7492a08e952b878053] app/controllers/articles_controller.rb:7:in `show'
```

**Comment by michelson** [comment]
try this:

> you could also put a `puts request.subdomain.first` in order to debug what's the value of the detected subdomain, in the line app/controllers/articles_controller.rb:15

**Comment by f10atin9** [comment]
> try this:
> 
> > you could also put a `puts request.subdomain.first` in order to debug what's the value of the detected subdomain, in the line app/controllers/articles_controller.rb:15

Can you please tell me what role HOST and WS play in the code? Maybe I can troubleshoot based on this.

**Comment by michelson** [comment]
Hi @f10atin9 , we have updated the subdomain checking to accept multi subdomain.

**Comment by leobaccili** [comment]
Same here

**Comment by leobaccili** [comment]
I used docker, I checked the ENV, everything looks fine but the error remains

**Comment by leobaccili** [comment]
rails_1     | 22:56:02 web.1  |   ArticleSetting Load (4.0ms)  SELECT "article_settings"."id", "article_settings"."domain", "article_settings"."subdomain", "article_settings"."properties", "article_settings"."app_id", "article_settings"."created_at", "article_settings"."updated_at" FROM "article_settings" WHERE "article_settings"."subdomain" = 'my.domain' LIMIT 1
rails_1     | 22:56:02 web.1  |   ↳ app/controllers/articles_controller.rb:14:in `messenger_data'
rails_1     | 22:56:02 web.1  | Completed 500 Internal Server Error in 41ms (ActiveRecord: 13.5ms | Allocations: 8782)
rails_1     | 22:56:02 web.1  | 
rails_1     | 22:56:02 web.1  | 
rails_1     | 22:56:02 web.1  | Not notifying due to an invalid api_key
rails_1     | 22:56:02 web.1  |   
rails_1     | 22:56:02 web.1  | NoMethodError (undefined method `app' for nil:NilClass):
rails_1     | 22:56:02 web.1  |   
rails_1     | 22:56:02 web.1  | app/controllers/articles_controller.rb:15:in `messenger_data'
rails_1     | 22:56:02 web.1  | app/controllers/articles_controller.rb:7:in `show'
rails_1     | 22:56:07 web.1  | Not delivering sessions due to an invalid api_key

**Comment by michelson** [comment]
> I used docker, I checked the ENV, everything looks fine but the error remains

what's your env HOST?

**Comment by leobaccili** [comment]
my.domain.com.br

**Comment by michelson** [comment]
you should add the protocol `http://`

**Comment by leobaccili** [comment]
sorry, i wrote wrong my answer, its http://my.domain.com.br

**Comment by michelson** [comment]
Are you testing that on a local environment?

**Comment by leobaccili** [comment]
No, test environment. VPS + docker + proxypass

**Comment by michelson** [comment]
Got it. it seems there is a bug on TLD with 2 levels.
a patch is on its way.

**Comment by michelson** [comment]
fix was released and docker latest published

**Comment by koopmac** [comment]
<img width="757" alt="image" src="https://user-images.githubusercontent.com/33947796/201044756-37c53a3f-1021-46c8-8e32-04cfe227679d.png">

Same issue - looks like you're missing .com.au in the locales
