### ISSUE TITLE
IP Tables error starting the system and Correct nginx config

### ISSUE THREAD

**Issue by TuxADN** [chaskiq/chaskiq#798]
Hello Miguel,
After your help yesterday I was able to complete the installation and start all apps individually, in different terminal sessions as indicated here:
https://dev.chaskiq.io/en/articles/docker-for-development

1) But I couldn't connect to the web panel getting 404 Not Found error in the browser and the console was showing the following error in the screen:
What's the correct nginx reverse proxy configuration?

chaskiq-rails-1  | 05:52:45 web.1  | 2022-08-19 05:52:45 +0000 HTTP parse error, malformed request: #<Puma::HttpParserError: Invalid HTTP format, parsing fails. Are you trying to open an SSL connection to a non-SSL Puma?>

My .env files shows the public domain with secure certificate already configured:

HOST=https://sub.domain.com
ASSET_HOST=https://sub.domain.com
WS=wss://sub.domain.com/cable

The above tried with reverse proxy enabled to none ssl:
proxy_pass http://sub.domain.com:3000/;

This config throws 502 Bad Gateway error in the web browser

Also:
I've tried the .env file with port 3000 and no reverse proxy 
That config throws 404 Not Found error in the web browser

2) So I brought the apps down and rebooted the server, now I'm getting the following error trying to run the system:
What ports does it need to be open in the firewall?
It seems to me like it's trying to do or looking for port redirecting in the firewall?

root@: /chaskiq# docker-compose up
WARN[0000] The "o2d" variable is not set. Defaulting to a blank string.
WARN[0000] The "o2d" variable is not set. Defaulting to a blank string.
WARN[0000] The "o2d" variable is not set. Defaulting to a blank string.
[+] Running 6/0
 ⠿ Container chaskiq-postgres-1  Created                                                                                          0.0s
 ⠿ Container chaskiq-redis-1     Created                                                                                          0.0s
 ⠿ Container chaskiq-rpc-1       Created                                                                                          0.0s
 ⠿ Container chaskiq-sidekiq-1   Created                                                                                          0.0s
 ⠿ Container chaskiq-runner-1    Created                                                                                          0.0s
 ⠿ Container chaskiq-rails-1     Created                                                                                          0.0s
Attaching to chaskiq-anycable-1, chaskiq-postgres-1, chaskiq-rails-1, chaskiq-redis-1, chaskiq-rpc-1, chaskiq-runner-1, chaskiq-sidekiq-1
Error response from daemon: driver failed programming external connectivity on endpoint chaskiq-redis-1 (bc1d3994ade76ed50597b845f7662263b3ca39c9b95029712b5ac03fc13c5b41):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 49346 -j DNAT --to-destination 172.X.X.X:6379 ! -i br-173acb53a9ce: iptables: No chain/target/match by that name.
 (exit status 1))
root@:~/chaskiq#

Your help is appreciated.
Thanks

**Comment by michelson** [comment]
Hi @TuxADN, I guess that you could try to use HTTP and not HTTPS for the local environment so your env looks like :

HOST=http://sub.domain.com/
ASSET_HOST=http://sub.domain.com/
WS=ws://sub.domain.com/cable

**Comment by TuxADN** [comment]
Hi Miguel,
I don't have a local setup, I'm actually trying to run the application in my public server.
That's why I rather prefer to have the system running on HTTPS right from the beginning, for security reasons of course.
This is on a fresh Ubuntu 20.04 server

So far what I understand, but I need your input if I'm correct about this, and I have some questions:

1) Install:
https://dev.chaskiq.io/en/articles/docker-for-development
(How do I check if everything is running fine at this point?)

2) Test:
https://dev.chaskiq.io/development/local-testing
(but I don't know what tests need to be performed)

3) Production:
https://dev.chaskiq.io/production-configuration
(There's no guide on how to set the docker installation for production)

4) What are the environment variables I need to set if I'm to use local storage, NOT AWS.
Well and the rest of environment variables for docker production.


Thanks for your help

**Comment by michelson** [comment]
but you are trying to run the development guide on a production server, that's not the intended way to do it. you should use the official Docker image that's already built. chaskiq:chaskiq
https://hub.docker.com/r/chaskiq/chaskiq/tags

**Comment by TuxADN** [comment]
Oh oh, Thanks a lot Miguel, it all makes sense now.
I'll check it out and let you know.

What's the minimum requirements for a server o VPS in order to run a Chaskiq instance?
CPU, RAM, Storage

**Comment by michelson** [comment]
a minimal instance would be a 2GB in which you can spawn a web process and a Sidekiq server, or two instances with 1GB each. In scenarios where you have more traffic a 2GB instance for web processes and 1GB for Sidekiq will be fine.

**Comment by TuxADN** [comment]
What's the location of the .env file once the docker hub image is pulled down?
In Ubuntu 20.04
I believe I need to edit the environment variables before I run the image.
Thanks

**Comment by michelson** [comment]
.env file is only for development,
 how you set env vars will vary on the platform you deploy the image.

**Comment by TuxADN** [comment]
Ok, in my case it's a fresh Ubuntu 20.04
I just ran the command:
docker pull chaskiq/chaskiq

Everything got downloaded successfully.

1)
How/Where do I set the environment variables?

2)
What's the appropriate command and options to run the Chaskiq docker image?



Thanks a lot

**Comment by michelson** [comment]
Where to put environment variables will vary on which platform are you using.

Please take some time to read the articles, this one shows how to deploy to Digitalocean with docker.
https://dev.chaskiq.io/production-configuration/production-deployment-on-digital-ocean-apps
