### ISSUE TITLE
Struck on  unf_ext 0.0.8 with native extensions

### ISSUE THREAD

**Issue by thespecialone1** [chaskiq/chaskiq#802]
First I encounter the ruby version error that 2.7.6 is not supported, only  2.7.5 is
then Installed the 2.7.5
ran this cmd
`bundle install`

Now its struck here 

![image](https://user-images.githubusercontent.com/76862693/186836258-baa8ebe6-49ee-4486-82ca-2048e63c9c69.png)

**Comment by MazanLabeeb** [comment]
Edit Gemfile

`sudo nano Gemfile`

replace the following line:

`gem "sassc"` 

with: 

`gem "sassc", "~> 2.1.0"`
