### ISSUE TITLE
Docker image installation showing

### ISSUE THREAD

**Issue by jimmy0017** [chaskiq/chaskiq#817]
I did a docker image installation with `REDIS_URL`, `DATABASE_URL`  and other environment variable from [this page](https://dev.chaskiq.io/en/articles/enviroment-variables-configuration).

I got the following error at the end. Do anybody know why? My environment variable is correct.

```
 !     App container failed to start (web.1)
=====> Start of chaskiq container output (web.1)
       [FATAL tini (6)] exec ANYCABLE_REDIS_URL= failed: No such file or directory
       [FATAL tini (6)] exec ANYCABLE_REDIS_URL= failed: No such file or directory
       [FATAL tini (7)] exec ANYCABLE_REDIS_URL= failed: No such file or directory
       [FATAL tini (7)] exec ANYCABLE_REDIS_URL= failed: No such file or directory
       [FATAL tini (7)] exec ANYCABLE_REDIS_URL= failed: No such file or directory
       [FATAL tini (8)] exec ANYCABLE_REDIS_URL= failed: No such file or directory
       [FATAL tini (6)] exec ANYCABLE_REDIS_URL= failed: No such file or directory
=====> End of chaskiq container output (web.1)
```

**Comment by michelson** [comment]
how are you starting the container? docker-compose up ?

**Comment by jimmy0017** [comment]
just the docker, without docker-compose.

**Comment by michelson** [comment]
how are you running it? did you put the required env variables?
are you using the chaskiq:chaskiq image or do you built it from source?

**Comment by michelson** [comment]
going to close this, feel free to reopen if you still having issues
