### ISSUE TITLE
Details of Article empty on Prod Server

### ISSUE THREAD

**Issue by Nuxor3000** [chaskiq/chaskiq#820]
Hi @michelson , I'm back after a period of illness and have some frre time to work on some identified issues.

I meet a problem with the HelpCenter. Maybe you can guide me. 

When I work locally : the detail sof the Article are shown when I click on one of the result after a search.
/package_iframe/ArticleSearch?data=...... => show the details

But on a prod server : the details are not shown.
/package_iframe/ArticleSearch?data=...... => show blank page

What am I missing ?

**Comment by michelson** [comment]
not sure really, did you test the same on chaskiq.io site?
the article search does an internal request to your server, maybe is there a problem with how the server internally requests itself, anyway you could try the latests build in which we have done some optimizations that avoids that internal request and renderers directly.

**Comment by michelson** [comment]
I think this issue was solved in the recent version, could you confirm this @Nuxor3000?
