### ISSUE TITLE
New apps permission

### ISSUE THREAD

**Issue by cms-infor** [chaskiq/chaskiq#831]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Chaskiq allow everyone to create new apps, wich is not suitable to all scenarios.

**Describe alternatives you've considered**
A way to prevent non-admins from creating new apps.
Also, if ther's only one, the non-admin user should be redirected to that app.

**Comment by michelson** [comment]
Hi there, you can use the `DISABLE_APP_CREATION=true` env var.

**Comment by cms-infor** [comment]
Thanks.
This solves my problem.

Still, there are situations where a permission would be ideal.
