### ISSUE TITLE
Propshaft::MissingAssetError in Home#show 

### ISSUE THREAD

**Issue by elvisxu** [chaskiq/chaskiq#855]
- OS:ubuntu 20.04.2 arm64
 - ruby:2.7.5
 - rails:7.0.4
<img width="804" alt="image" src="https://user-images.githubusercontent.com/16045587/202415214-2bca2ffb-dbbb-4804-aee1-f1aa5df6f13f.png">

**Comment by michelson** [comment]
did you run the asset precompilation with `yarn dev` ?

**Comment by michelson** [comment]
reopen if you need more help, closing now.

**Comment by elvisxu** [comment]
<img width="805" alt="image" src="https://user-images.githubusercontent.com/16045587/202601029-d540807f-5ec5-4e07-9c3f-4cdced9d0e77.png">
<img width="776" alt="image" src="https://user-images.githubusercontent.com/16045587/202601069-6b5e53c8-1c99-4447-9142-2e1446d89469.png">

**Comment by michelson** [comment]
uhmm... odd. what happens if you comment that line?

**Comment by elvisxu** [comment]
the app lost all style.

**Comment by elvisxu** [comment]
I found I can't find the tailwind.css in /app/assets/builds/, I try to rename one css file as tailwind.css, then restart the application, the result is the picture as I uploaded.
<img width="890" alt="image" src="https://user-images.githubusercontent.com/16045587/202609261-89567f3f-a0c7-49c1-bc98-3a341bba3921.png">

**Comment by michelson** [comment]
ok, try updating node to version 17

**Comment by michelson** [comment]
did it work? I will close this for now, reopen if you need more help on this topic.
