### ISSUE TITLE
Site cannot be reached after Ubuntu development setup guide folllowed

### ISSUE THREAD

**Issue by TwoBrake** [chaskiq/chaskiq#902]
**Describe the bug**
I followed all the setup steps for the Ubuntu development setup guide and when I start the rails server, it successfully starts, but when I go to the domain I setup in the `/etc/hosts` file, it just says the site can't be reached.

**To Reproduce**
1. Follow the Ubuntu development setup guide.
2. Go to your domain you setup.

**Screenshots**
![image](https://user-images.githubusercontent.com/78281961/213793511-fae9e427-771d-4f47-bf38-0e22c254b00b.png)

**Comment by michelson** [comment]
Probably you are not writing the domain properly. Are you adding the port?
what does the server log say?

**Comment by TwoBrake** [comment]
How do I check the server logs?

**Comment by michelson** [comment]
In the shell console where you are starting the server ...

**Comment by TwoBrake** [comment]
I mean, what command do I run?

**Comment by TwoBrake** [comment]
Here are the logs.

[development.log](https://github.com/chaskiq/chaskiq/files/10470212/development.log)

**Comment by TwoBrake** [comment]
Just letting you know that I changed the port from 3000 to 3003 since port 3000 was taken.

**Comment by michelson** [comment]
it seems that you didn't start the server, the logs only shows the database configuration and the seed. 
what's the command that you are using to start the server?

**Comment by TwoBrake** [comment]
> it seems that you didn't start the server, the logs only shows the database configuration and the seed. 
> what's the command that you are using to start the server?

`bundle exec rails server`

**Comment by michelson** [comment]
what's the log for that command? can you send me that specific log, when you enter the `rails server` in the console send what's happen next.

**Comment by TwoBrake** [comment]
These are both the log files inside my `/log` folder.
[scout_apm.log](https://github.com/chaskiq/chaskiq/files/10471348/scout_apm.log)
[development.log](https://github.com/chaskiq/chaskiq/files/10471349/development.log)

**Comment by michelson** [comment]
that log shows that is creating the database, you are not running the server yet.
when you start the server you should see this:

![image](https://user-images.githubusercontent.com/11976/213840801-4be1ab7f-8db0-4efa-ae64-b0849dce2e9d.png)
can you show me that log? with the command and all?

**Comment by TwoBrake** [comment]
Yes, it shows that, is there something else I have to do?

**Comment by michelson** [comment]
can you show me?

**Comment by TwoBrake** [comment]
Here you go.
![image](https://user-images.githubusercontent.com/78281961/213840906-9a6105c5-8514-4f6b-8c6b-1e5a0bea2d15.png)

**Comment by michelson** [comment]
ok, what happens if you visit localhost:3003 ?
did you configure the .env file with the HOST? if the HOST is foo.test, then you need to visit foo.test:3003 in your browser

**Comment by TwoBrake** [comment]
The `.env` file is configured with my sub domain that points to the server. Do you want me to send you the `.env` file and `/etc/hosts` file?

**Comment by michelson** [comment]
in another in console run `yarn dev` that will precompile the assets (js / css) 
what do you have in the /etc/hosts for the domain ? and what do you have in the HOST / WS in the .env file? 
is the env file named as `.env` right?

**Comment by TwoBrake** [comment]
Yes the .env file is called `.env`. I provided the files below.
.env file:

```

HOST=http://agent.twobrake.xyz:3003
ASSET_HOST=http://agent.twobrake.xyz:3003
WS=ws://agent.twobrake.xyz/cable

SNS_CONFIGURATION_SET=metrics

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=

AWS_S3_BUCKET=
AWS_S3_REGION=us-east-1

FULLCONTACT_TOKEN=

ADMIN_EMAIL=admin@example.com
ADMIN_PASSWORD=password

DEFAULT_SENDER_EMAIL=admin@example
```
hosts file:
```
127.0.0.1	localhost
127.0.0.1   agent.twobrake.xyz

```

**Comment by michelson** [comment]
ok, for local environments you will need to use .test as a tld, so change .xyz by .test

**Comment by TwoBrake** [comment]
In the hosts file or the .env file?

**Comment by michelson** [comment]
both

**Comment by TwoBrake** [comment]
What would I enter in the browser then?

**Comment by TwoBrake** [comment]
Would I still enter the `.xyz` domain?

**Comment by michelson** [comment]
change it from this agent.twobrake.xyz to this agent.twobrake.test 
in the browser visit agent.twobrake.test:3003 
note that the port is needed in the .env file

**Comment by TwoBrake** [comment]
It still doesn't work. Just letting you know that the sub domain is a domain that I own and it is running on a server.

**Comment by TwoBrake** [comment]
How would `.test` work?

**Comment by michelson** [comment]
oh, are you running this on development mode? production mode? on a server ? not localhost?

**Comment by TwoBrake** [comment]
It is on a server, not localhost.

**Comment by TwoBrake** [comment]
But the project is in development mode.

**Comment by TwoBrake** [comment]
Does it not work if it is on development mode?

**Comment by michelson** [comment]
Production application should be run with a production image, not a development environment. For the domain to work you will need to add some nginx proxy server in between or use services like heroku, or digital ocean (apps), we have some guides for both.

**Comment by TwoBrake** [comment]
Do I still need the domain in the `/etc/hosts` file?

**Comment by michelson** [comment]
`/etc/hosts` is just for local testing, it will not work for the outside world.
I will close this issue now as this is not intended way to deploy chaskiq. You have followed a development guide trying to deploy to production. That is not the intended way.
Feel free to open a new issue if you get stuck in any of the other production deployment guides. I suggest that you use digital ocean apps.
