### ISSUE TITLE
Nginx reverse proxy 502 bad gateway

### ISSUE THREAD

**Issue by TwoBrake** [chaskiq/chaskiq#903]
**Describe the bug**
I have setup an Nginx reverse proxy pointing to the server address and port but when I go to my domain it says 502 bad gateway.

**To Reproduce**
1. Follow the installation guide.
2. Setup Nginx reverse proxy pointing to the server address.
3. Open browser and enter the sub domain you setup.

**Screenshots**
<img width="440" alt="image" src="https://user-images.githubusercontent.com/78281961/213842745-b96dad17-5f3b-4966-aee2-7e3e796c79f5.png">
<img width="295" alt="image" src="https://user-images.githubusercontent.com/78281961/213842767-16fe952d-8ab4-4c21-8d7c-4926ca106702.png">

**Comment by michelson** [comment]
> 502 bad gateway.

What do the logs say?

> Follow the installation guide.

Which one?

If you don't use SSL (https & wss) connection, the WebSocket will not work, so the chat will not work either

**Comment by TwoBrake** [comment]
These are the files in my `/log` folder.
[development.log](https://github.com/chaskiq/chaskiq/files/10472602/development.log)
[scout_apm.log](https://github.com/chaskiq/chaskiq/files/10472603/scout_apm.log)

**Comment by michelson** [comment]
which installation guide are you following?
also, the file you are sending is not the server log. I've already explained this to you on the other issue that you have opened. If you are using the development guide for production that will not work fine

**Comment by TwoBrake** [comment]
I have configured the environment variable to use production mode. Those are the only log files that exist in the `/log` folder.

**Comment by michelson** [comment]
which installation guide are you following?

**Comment by TwoBrake** [comment]
https://dev.chaskiq.io/production-configuration/enviroment-variables-configuration

**Comment by michelson** [comment]
That's not an installation guide :( 
I suggest that you read the deployment guides that we support. 
I really can't give you support on this custom deployment, anyway deploying rails apps with Nginx is widely documented, so if you want to persist with it I suggest that you read how it works or get someone who knows how to do it for you. 
Closing the ticket now
