### ISSUE TITLE
rails admin_generator is not working to setup the admin password

### ISSUE THREAD

**Issue by jesusalc** [chaskiq/chaskiq#904]
Following the task 
rails admin_generator

does not work

<img width="611" alt="Screenshot 2023-01-21 at 15 51 18" src="https://user-images.githubusercontent.com/1438028/213874111-afffe573-b90e-406c-8ea7-9c8c453a3c3b.png">

**Comment by jesusalc** [comment]
NoMethodError: undefined method `add_admin' for nil:NilClass

**Comment by michelson** [comment]
you need to run `rails db:seed` before run the admin_generator

**Comment by jesusalc** [comment]
I  got it to work, but i had to change several files 
<img width="1671" alt="Screenshot 2023-01-21 at 17 29 44" src="https://user-images.githubusercontent.com/1438028/213876778-d604610f-2704-4aba-9a48-87746d7482eb.png">
I  got it to work, but i had to change several files  
changed all 
localhost:3000 to 120.0.0.1:3000
also had to do 

bin/rails db:environment:set RAILS_ENV=development
then reset the db again

bundle exec rake db:setup
bundle exec rake db:migrate
 bundle exec rake db:seed

**Comment by jesusalc** [comment]
rails admin_generator 
finally

**Comment by jesusalc** [comment]
maybe I should make a a PR request ?

**Comment by michelson** [comment]
Which files did you have to change?

**Comment by jesusalc** [comment]
(base) ➜  chaskiq git:(master) ✗ gsb
## master...origin/master
 M .gitignore
 M app/javascript/packages/store/src/actions/auth.ts
 M app/models/message.rb
 M app/services/message_apis/dialog360/api.rb
 M app/services/message_apis/twilio_phone/api.rb
 M config/environments/development.rb
 M lib/omniauth/strategies/doorkeeper.rb
 M spec/controllers/api/graphql_controller_spec.rb
 M spec/factories/factories.rb
 M spec/mailers/previews/campaign_preview.rb
 M spec/mailers/previews/chat_notifier_preview.rb

**Comment by michelson** [comment]
why!? that does not make sense. can you send the git diff of that changes?

**Comment by jesusalc** [comment]
like I said localhost and 127.0.0.1 seems to be a problem with ruby, like they are not synonyms

**Comment by michelson** [comment]
seems to me that you just did search & replace without look what code were you changing. mostly all the `localhost:3000` that you have changed is commented code.

**Comment by jesusalc** [comment]
true at that.
[rename_localhost_to_127001.patch](https://github.com/chaskiq/chaskiq/files/10472611/rename_localhost_to_127001.patch)

**Comment by jesusalc** [comment]
I also made sure redis was running before

**Comment by michelson** [comment]
those changes are not neccesary, I ussually use localhost for local dev and I've just tried 127.0.0.1 and it is working ok, proof:

![image](https://user-images.githubusercontent.com/11976/213877995-2d00c4de-d423-4855-be6f-6f65f36dcb04.png)

**Comment by michelson** [comment]
I'm going to close this as it seems that you solved it anyway. 
best
