### ISSUE TITLE
deploy heroku - slug-size

### ISSUE THREAD

**Issue by renygrando** [chaskiq/chaskiq#908]
`-----> Discovering process types
       Procfile declares types     -> web, worker
       Default types for buildpack -> console, rake
-----> Compressing...
 !     Compiled slug size: 602.2M is too large (max is 500M).
 !     See: http://devcenter.heroku.com/articles/slug-size
 !     Push failed`

**Comment by michelson** [comment]
Hi Reny, I guess that you could try building a post build script that deletes node_modules
https://devcenter.heroku.com/articles/nodejs-support#heroku-specific-build-steps
didn't try it but it should work

**Comment by shishircse06** [comment]
Hey @renygrando , did you fix the issue? I'm facing the same problem.

**Comment by renygrando** [comment]
unfortunately not. I ended up not needing to use it.
