### ISSUE TITLE
Not open source (according to the OSI definition)

### ISSUE THREAD

**Issue by fpesari** [chaskiq/chaskiq#925]
Hello,

in the README.md, chaskiq says that it is an "Open Source Messaging Platform for Marketing, Support & Sales" but its license (AGPLv3 with a "Commons Clause" which forbids commercial usage) is not approved by the OSI, so it's not "open source". The first criterion from the OSI's open source definition says that ([source](https://opensource.org/osd/)):

> The license **shall not restrict any party from selling or giving away the software as a component of an aggregate software** distribution containing programs from several different sources. The license shall not require a royalty or other fee for such sale.

Moreover, the FSF considers the Commons Clause nonfree ([source](https://www.gnu.org/licenses/license-list.en.html#comclause)).

I am not criticizing you in any way, I understand that it's your business model and I don't want to damage it in any way, however this is a misuse of the "open source" term and should be amended (maybe with "source-available" or a similar expression) for clarity and to avoid unwilling violations. Thank you.

**Comment by michelson** [comment]
done, thanks for the heads up

**Comment by ahangarha** [comment]
@michelson Thanks for considering @fpesari comment and taking action accordingly.

I would like to suggest you to check out [BSL license](https://mariadb.com/bsl11/) which might provide even better protection to your business model while guaranteeing full AGPL in the future.

**Comment by ssddanbrown** [comment]
@michelson Looks like the website also needs updating? mulitple references to being open source on your homepage alone:

> Open source from the start

> Chaskiq is an open source platform that connects and empowers  [...]

> Chaskiq is an Open Source Messaging Platform for Marketing, Support & Sales.
