### ISSUE TITLE
does not work on centos 7

### ISSUE THREAD

**Issue by powerweb4you** [chaskiq/chaskiq#962]
I installed it but it doesn't work on centos 7

**Comment by michelson** [comment]
Hi how you installed it? are you running dev mode?

please send some error trace if you have

**Comment by powerweb4you** [comment]
So you want to set up Chaskiq on Ubuntu to hack on and develop with? We’ll assume that you have Ruby/Rails/Postgre/Redis installed on your Ubuntu system. Let’s begin!.

First. you will need to install the following requirements for installation.

Git
Ruby (2.7) we recommend rvm to manage ruby versions
Rails
PostgreSQL
Redis
Bundler
ImageMagick

**Comment by michelson** [comment]
please use docker . Docker images are working and also work on our CI.

**Comment by powerweb4you** [comment]
Docker also does not work on there is no clearer explanation about this. Docker is installed on centos 7

**Comment by powerweb4you** [comment]
https://dev.chaskiq.io/getting-started/docker-for-development

[root@localhost ~]# docker-compose build
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
        
[root@localhost ~]# docker-compose run rails rails db:create
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
        
[root@localhost ~]# docker-compose build
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
        
[root@localhost ~]#

**Comment by michelson** [comment]
docker-compose.yml is on the root of the application. probably you are not calling the command inside the chaskiq folder.

**Comment by powerweb4you** [comment]
\also tried also does not work (Ubuntu) everything installed Git
Ruby (2.7) we recommend rvm to manage ruby versions
rails
PostgreSQL
redis
bundler
ImageMagick

get this error


Caused by:
PG::ConnectionBad: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL: Peer authentication failed for user "postgres"
/home/admin2/chaskiq/app/models/app.rb:58:in `<class:App>'
/home/admin2/chaskiq/app/models/app.rb:5:in `<main>'
/home/admin2/chaskiq/lib/tasks/admin_generator.rake:3:in `block in <main>'
Tasks: TOP => admin_generator
(See full trace by running task with --trace)
admin2@admin2-VMware-Virtual-Platform:~/chaskiq$
Caused by:
PG::ConnectionBad: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL: Peer authentication failed for user "postgres"
/home/admin2/chaskiq/app/models/app.rb:58:in `<class:App>'
/home/admin2/chaskiq/app/models/app.rb:5:in `<main>'
/home/admin2/chaskiq/lib/tasks/admin_generator.rake:3:in `block in <main>'
Tasks: TOP => admin_generator
(See full trace by running task with --trace)

**Comment by powerweb4you** [comment]
[root@localhost ~]# sudo docker run -ti --rm chaskiq/chaskiq /bin/bash
docker@44f8db49c7b6:/usr/src/app$ (centos 7)

**Comment by powerweb4you** [comment]
[root@localhost support]# docker-compose up rails
support_postgres_1 is up-to-date
support_redis_1 is up-to-date
Starting support_rails_1 ... error

ERROR: for support_rails_1  Cannot start service rails: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./bin/dev": permission denied: unknown

ERROR: for rails  Cannot start service rails: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./bin/dev": permission denied: unknown
ERROR: Encountered errors while bringing up the project.
[root@localhost support]#
