### ISSUE TITLE
After successfully deployment with docker compose only a blankk page comes up

### ISSUE THREAD

**Issue by Olive-harobed** [chaskiq/chaskiq#983]
Hello, after a successful deployment of the application with docker, the webpage pull up blank with a 200 response

**Expected behavior**
I expected that a landing page or login page will be presented on successful deployment
**Screenshots**
![image](https://github.com/chaskiq/chaskiq/assets/79452458/3be09bbe-87e8-456b-817c-8a972ae62e21)
![image](https://github.com/chaskiq/chaskiq/assets/79452458/0b45da5b-adb6-4113-827c-31751b91d6eb)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Browser [chrome, safari, edge]

**Comment by michelson** [comment]
Hi, if you use chaskiq for production, please use the official docker image at chaskiq:chaskiq. You are probably using the docker for development.
